import type { RegionDef } from '../course'

/**
 * C 基础 · 区域 1：打印码头
 *
 * 每关 6 题、Boss 关 9 题，五种题型混用，每关至少 1 道填空 + 1 道找错。
 * 全部 output 题的运行结果、bug 题的报错行、fill/order 的拼装结果，
 * 均已用本机 gcc -std=c99 -Wall 真机编译运行验算。
 */
export const regionC1: RegionDef = {
  id: 'c1',
  name: '打印码头',
  tagline: '一切冒险从屏幕上的第一行字开始',
  levels: [
    // ============ c1-1 printf 与转义 ============
    {
      id: 'c1-1',
      name: '鸣笛启航',
      xp: 40,
      gold: 14,
      learn: {
        title: 'printf：码头的扩音器',
        body: [
          'C 程序从 main 函数起航，printf 是你手里的扩音器，把文字喊到屏幕上。它住在标准输入输出库里，文件第一行要写 #include <stdio.h> 把装备借来。',
          '双引号里是想喊的话；在句子末尾写 \\n 是「换行」暗号——printf 绝不自动换行，想分几行就得写几个 \\n。',
          '%d、%s、%c 是三个占位符：%d 留给整数、%s 留给字符串、%c 留给单个字符。printf 会把后面的值按顺序填进这些空位。',
          'main 的返回类型是 int，最后一行 return 0; 是向系统报平安——0 是约定俗成的「一切正常」暗号。',
        ],
        code: '#include <stdio.h>\n\nint main(void) {\n    printf("Ahoy! %d 级水手 %s\\n", 7, "小旗");\n    printf("金币:%d%c\\n", 99, \'G\');\n    return 0;\n}\n/* 输出：\n   Ahoy! 7 级水手 小旗\n   金币:99G */',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '在 C 里，想让 printf 输出完换到下一行，要在字符串里写什么？',
          options: ['/n', '\\n', '<br>', '什么都不用写，printf 会自动换行'],
          answerIndex: 1,
          hint: '是反斜杠，别把方向写反了。',
          explain: 'C 用反斜杠 \\n 表示换行（n = newline）。正斜杠 /n 没有特殊含义，会被原样打印成 "/n"；<br> 是网页的标签，和 C 无关。printf 绝不自动换行——这是新手最常踩的坑之一，想让输出分两行，就得写两个 \\n。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后，屏幕上是什么样子？',
          code: '#include <stdio.h>\nint main(void) {\n    printf("HP:%d\\n", 100);\n    printf("MP:%d\\n", 30);\n    return 0;\n}',
          options: ['HP:100 和 MP:30 分两行显示', 'HP:100MP:30 挤在同一行', 'HP:%d 和 MP:%d 原样打印', '编译报错'],
          answerIndex: 0,
          hint: '每个字符串的末尾都藏着 \\n。',
          explain: '两行 printf 各带一个 \\n，所以各占一行：先输出 HP:100 然后换行，再输出 MP:30 再换行。要是把两个 \\n 都删掉，输出会挤成一行：HP:100MP:30。占位符 %d 则被后面的 100、30 按顺序填上。',
        },
        {
          kind: 'fill',
          prompt: '补全占位符，让这行代码输出「金币:99」：',
          code: '#include <stdio.h>\nint main(void) {\n    printf("金币:___\\n", 99);\n    return 0;\n}',
          answers: ['%d'],
          placeholder: '以 % 开头的整数占位符',
          hint: '99 是整数，得用整数的占位符。',
          explain: '%d 是整数占位符（d = decimal，十进制），printf 会把后面的 99 填进这个空位。写成 %s 会把 99 当成字符串的地址去读——这是未定义行为，轻则乱码重则崩溃。占位符和值的类型必须门当户对。',
        },
        {
          kind: 'bug',
          prompt: '下面几行里，哪一行会让编译器直接报错？',
          code: ['#include <stdio.h>', 'int main(void) {', '    printf("起航\\n");', '    return o;', '}'],
          answerLine: 3,
          hint: 'return 后面那个应该是数字零。',
          explain: '第 4 行把数字 0 写成了字母 o。C 编译器把 o 当成一个从没声明过的变量名，当场报错：\'o\' undeclared（o 未声明）。return 0; 的 0 是数字零，表示程序正常结束——字母 o 和数字 0 长得像，但在 C 里是完全两码事。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行拖回正确顺序，拼出一个能编译的最小 C 程序：',
          lines: ['#include <stdio.h>', 'int main(void) {', '    printf("码头到了\\n");', '    return 0;', '}'],
          hint: '先借装备（#include），再搭 main 的船身，然后喊话、报平安，最后收口。',
          explain: '最小 C 程序的骨架：#include <stdio.h> 把 printf 所在的装备库借来；int main(void) { 是整艘船的入口；printf 负责喊话（每条语句以分号收尾）；return 0; 向系统报告「航行正常」；最后的 } 把船身合拢。顺序不能乱，缺一行都不完整。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    printf("%s%c\\n", "Ahoy", \'!\');\n    return 0;\n}',
          options: ['Ahoy!', 'Ahoy', 'Ahoy!%c', '报错'],
          answerIndex: 0,
          hint: '%s 吃字符串，%c 吃单个字符。',
          explain: '%s 被字符串 "Ahoy" 填上，%c 被单个字符 \'!\' 填上，拼起来正好是 Ahoy!。注意：单引号包一个字符（\'!\'），双引号包字符串（"Ahoy"）——在 C 里这俩不是一回事，字符常量 \'!\' 其实是个小整数，而 "Ahoy" 是一串字符。',
        },
        {
          kind: 'output',
          prompt: '这行代码输出什么？',
          code: 'printf("%d+%d=%d\\n", 2, 3, 5);',
          options: ['2+3=5', '5=5', '%d+%d=%d', '报错'],
          answerIndex: 0,
          hint: '三个占位符按顺序吃三个值。',
          explain: '%d 出现三次，后面的 2、3、5 按顺序填入，+ 和 = 原样输出，得 2+3=5。占位符与值的顺序、数量、类型必须一一对应。',
        },
        {
          kind: 'choice',
          prompt: 'printf("第一行\\n第二行\\n"); 会输出几行？',
          options: ['一行', '两行', '三行', '什么都不输出'],
          answerIndex: 1,
          hint: '数一数字符串里有几个 \\n。',
          explain: '两个 \\n 各制造一次换行：第一行「第一行」、第二行「第二行」。printf 绝不自动换行，几行输出全看写了几个 \\n。',
        },
        {
          kind: 'choice',
          prompt: "'A' 和 \"A\" 是一回事吗？",
          options: ['是，都表示字母 A', "不是：'A' 是单个字符，\"A\" 是字符串（末尾还多一个 \\0）", '都是字符串', '都是整数'],
          answerIndex: 1,
          hint: '单引号和双引号在 C 里是两个世界。',
          explain: "'A' 是字符常量（本质是小整数 65）；\"A\" 是字符串，除了字母 A 还有一个看不见的 '\\0' 结尾。两者类型不同，混用会出问题——比如把 \"A\" 交给 %c 打印。",
        },
      ],
    },

    // ============ c1-2 变量与类型 ============
    {
      id: 'c1-2',
      name: '货箱与标签',
      xp: 42,
      gold: 15,
      learn: {
        title: '变量与类型：给货物贴对标签',
        body: [
          '变量是贴了标签的货箱，声明时要写明类型：int 装整数，float 和 double 装小数（double 精度更高、更常用），char 装单个字符。',
          'printf 打印小数用 %f，默认显示 6 位小数（3.14 会变成 3.140000）；想只留 2 位就写 %.2f，留 1 位就写 %.1f。',
          'char 用单引号装一个字符：char rank = \'S\';。字符在 C 的眼里其实是个小整数——\'A\' 就是编号 65，所以字符也能参与运算。',
          'const 是「封箱胶带」：const int MAX_HP = 100; 之后谁也别想改它，改了编译器直接报错。常量名习惯全大写，一眼认出「这是封了箱的」。',
        ],
        code: 'int hp = 100;            // int：整数\ndouble gold = 12.5;      // double：小数\nchar rank = \'S\';         // char：单字符，单引号\nconst int MAX_HP = 999;  // const：封顶不改\nprintf("%.2f\\n", gold);  // → 12.50\nprintf("%d\\n", 7 / 2);   // → 3（整数除法砍掉小数）',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '想存一个精度较高的小数 3.14159，哪种声明最合适？',
          options: ['int pi = 3.14159;', 'double pi = 3.14159;', 'char pi = 3.14159;', 'pi := 3.14159;'],
          answerIndex: 1,
          hint: 'int 只能装整数，char 装单个字符。',
          explain: 'double 是双精度浮点型，装小数最合适。用 int 装 3.14159，小数部分会被直接砍掉只剩 3（不是四舍五入）；char 只能装一个字符；pi := 3.14159 是别的语言的写法——C 声明变量必须先写类型。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    double gold = 12.5;\n    printf("%.2f\\n", gold);\n    return 0;\n}',
          options: ['12.5', '12.50', '12.500000', '13'],
          answerIndex: 1,
          hint: '%.2f 表示「显示到小数点后 2 位」，位数不够就补 0。',
          explain: '%.2f 把数值固定显示成 2 位小数：12.5 只有一位，补零变成 12.50。裸的 %f 才会显示 6 位小数（12.500000）。金币、胜率这类要账面整齐的数值，游戏里常用 %.Nf 控制位数。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    printf("%d\\n", 7 / 2);\n    printf("%.1f\\n", 7.0 / 2);\n    return 0;\n}',
          options: ['3 和 3.5', '3.5 和 3.5', '3 和 3.0', '4 和 3.5'],
          answerIndex: 0,
          hint: '两个整数相除，小数部分去哪了？',
          explain: '7 / 2 两边都是 int，C 做整数除法：小数部分直接扔掉（不是四舍五入），得 3。第二行 7.0 / 2 有一边是小数，整场除法升级成浮点除法，得 3.5，%.1f 显示 3.5。想让商带小数，运算前至少一边得是小数——这是 C 的经典暗坑。',
        },
        {
          kind: 'bug',
          prompt: '这段代码编译报错，错在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    const int MAX_HP = 100;', '    MAX_HP = 200;', '    printf("上限:%d\\n", MAX_HP);', '    return 0;', '}'],
          answerLine: 3,
          hint: '贴了 const 封条的货箱，还能拆开重装吗？',
          explain: '第 4 行想给 const 常量赋新值，编译器当场拒绝：assignment of read-only variable（给只读变量赋值）。const 就是封箱胶带，封上之后任何修改都是编译错误——这正是 const 的价值：谁也改不了的上限，写错立刻暴露，而不是悄悄埋雷。',
        },
        {
          kind: 'fill',
          prompt: '补全类型关键字，把评级 S 装进变量：',
          code: '___ rank = \'S\';\nprintf("%c\\n", rank);   /* → S */',
          answers: ['char'],
          placeholder: '一个四字母的类型名',
          hint: '装单个字符的类型，四个字母。',
          explain: 'char 是字符型，用单引号装一个字符：char rank = \'S\';。注意单引号和双引号在 C 里是两种东西：\'S\' 是单个字符，"S" 是字符串（末尾还多一个看不见的结束符 \\0），类型完全不同，混用会出问题。',
        },
        {
          kind: 'output',
          prompt: '用 %d 打印一个 char，会输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    char c = \'A\';\n    printf("%d\\n", c);\n    return 0;\n}',
          options: ['A', '65', '0', '报错'],
          answerIndex: 1,
          hint: '字符在 C 的眼里其实是个号码。',
          explain: 'char 本质是个小型整数，每个字符在 ASCII 表里都有编号：\'A\' 是 65。用 %c 打印显示字符本身 A，用 %d 打印显示编号 65。「字符即整数」是 C 的重要设定，也是字符能做运算的原因。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出什么？',
          code: 'int a = 7, b = 2;\nprintf("%d\\n", a / b);',
          options: ['3.5', '3', '4', '报错'],
          answerIndex: 1,
          hint: '两个 int 相除，小数部分去哪了？',
          explain: 'int / int 是整数除法：7 ÷ 2 商 3 余 1，结果直接砍掉小数得 3（不是四舍五入）。想得 3.5，至少一边写成小数：7.0 / 2。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出什么？',
          code: 'printf("%.1f\\n", 2.54);',
          options: ['2.54', '2.5', '2.6', '3'],
          answerIndex: 1,
          hint: '%.1f 保留 1 位小数。',
          explain: '%.1f 把 2.54 四舍五入到 1 位小数，得 2.5。点号后的数字控制小数位数：%.2f 两位、%.0f 整数。账面数值要几位就点几位。',
        },
        {
          kind: 'fill',
          prompt: '补全类型名，装下精度更高的小数：',
          code: '___ gravity = 9.8;   /* 常用的小数类型，双精度 */',
          answers: ['double'],
          placeholder: '六个小写字母的类型名',
          hint: 'float 的加强版。',
          explain: 'double 是双精度浮点型，比 float 精度高，是 C 里装小数的首选。printf 打印它用 %f；注意 scanf 读它要用 %lf——读和打的规矩不通用。',
        },
      ],
    },

    // ============ c1-3 scanf 与取地址 ============
    {
      id: 'c1-3',
      name: '入港登记',
      xp: 44,
      gold: 16,
      learn: {
        title: 'scanf：入港登记处',
        body: [
          'scanf 是反向的 printf：printf 往屏幕喊，scanf 从键盘收货。写法是 scanf("%d", &hp);——把用户敲的整数存进变量 hp。',
          '& 是「取地址」符，&hp 意思是「hp 这个货箱的地址」。scanf 必须知道地址才能把货放进去；忘了 &，它会把值砸到不可知的地方，程序当场崩溃。',
          '格式符必须和变量类型配对：%d 配 int 的地址；scanf 读 double 要用 %lf（注意和 printf 的 %f 不一样！），读 float 才用 %f；%c、%s 各归各位。',
          '一次可以读多个：scanf("%d %d", &a, &b);——用户用空格或回车分隔都行，两个整数会按顺序填进 a 和 b。',
        ],
        code: 'int hp;\nscanf("%d", &hp);        // &hp：hp 的地址，& 千万别丢\ndouble gold;\nscanf("%lf", &gold);     // scanf 读 double 用 %lf\nint a, b;\nscanf("%d %d", &a, &b);  // 一次读两个，空格分隔',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'scanf("%d", &hp); 里的 & 是干什么用的？',
          options: ['装饰品，写不写都行', '取出 hp 的内存地址，告诉 scanf 把值存到哪', '把 hp 里的旧值交给 scanf', '表示「并且」，和 if 里的 && 一样'],
          answerIndex: 1,
          hint: 'scanf 得先知道货往哪个货箱放。',
          explain: '& 是取地址符，&hp 拿到 hp 在内存里的地址。scanf 拿着地址，才能把用户输入的值准确放进那个货箱。少了 &，scanf 拿到的只是 hp 里的垃圾旧值，还会把它当成地址乱写内存——程序十有八九当场崩溃。',
        },
        {
          kind: 'choice',
          prompt: '执行 scanf("%d %d", &a, &b); 时，用户输入了 12 7（中间一个空格），a 和 b 分别是多少？',
          options: ['a 得 12，b 得 7', 'a 得 127，b 得 0', 'a 得 7，b 得 12', '程序当场崩溃'],
          answerIndex: 0,
          hint: '两个 %d 按顺序吃掉两个数，空格只是分隔符。',
          explain: 'scanf("%d %d", &a, &b) 按顺序找两个整数：12 填给 a，7 填给 b。用户用空格、Tab 或回车分隔都行，%d 会自动跳过空白。决定对应关系的不是空格，而是占位符的顺序——第 1 个 %d 对第 1 个地址，第 2 个 %d 对第 2 个地址。',
        },
        {
          kind: 'fill',
          prompt: '补上一个符号，让 scanf 能把值正确存进 hp：',
          code: 'int hp;\nscanf("%d", ___hp);   /* 缺了个关键符号 */',
          answers: ['&'],
          placeholder: '一个取地址符号',
          hint: '「hp 这个货箱在哪」的那个符号，单个字符。',
          explain: '在 hp 前面补上 & 变成 &hp，scanf 拿到地址才能存值。原样写 scanf("%d", hp) 编译能过（顶多警告），但运行时 scanf 会把 hp 里的垃圾值当地址乱写——未定义行为，九成九当场崩溃。这颗雷写的时候毫无感觉，跑起来才炸。',
        },
        {
          kind: 'bug',
          prompt: '这段代码能通过编译（只有警告），但运行必出事。雷埋在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    double gold = 0;', '    scanf("%f", &gold);', '    printf("%.2f\\n", gold);', '    return 0;', '}'],
          answerLine: 3,
          hint: 'scanf 读 double 的格式符，和 printf 的不一样。',
          explain: '第 4 行的雷：scanf 读 double 必须用 %lf。写 %f 时 gcc 的警告说得很直白——format \'%f\' expects argument of type \'float *\'（%f 只往 4 字节的 float 里塞），而你递给它 8 字节的 double 的地址，只塞进去一半，数值面目全非。实测输入 3.5，打印出来是 0.00。同一个变量，printf 打印用 %f、scanf 读取用 %lf——读和打的规矩不通用。',
        },
        {
          kind: 'order',
          prompt: '登记处流程排序：声明货箱、收货、加工、出货。把四行拖回正确顺序：',
          lines: ['int gold;', 'scanf("%d", &gold);', 'gold = gold + 5;', 'printf("金币:%d\\n", gold);'],
          hint: '先有箱子（声明）才能收货（scanf），先收货才有的加工。',
          explain: 'C 要求先声明再使用：int gold; 造出货箱；scanf 收货进 &gold；gold = gold + 5 加工（右边先算完旧值加 5，再放回 gold）；printf 出货。任何一步提前，编译器要么不认识 gold，要么加工的是没收到的货。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    printf("%s got %d gold\\n", "Crew", 30);\n    return 0;\n}',
          options: ['Crew got 30 gold', '%s got %d gold', 'Crew got gold', '报错'],
          answerIndex: 0,
          hint: '占位符按从左到右的顺序，挨个吃后面的值。',
          explain: '%s 吃 "Crew"，%d 吃 30，其余字符（got、gold、空格）原样输出。printf 和 scanf 守同一条规矩：占位符与值必须类型配对、顺序对应、数量相等。这个规矩到哪张桌子上都一样。',
        },
        {
          kind: 'choice',
          prompt: 'scanf("%d %d", &a, &b); 用户先输入 3 按回车，再输入 7 按回车，a 和 b 分别是？',
          options: ['a=3, b=7', 'a=37, b=0', 'a=3, b=0', '程序崩溃'],
          answerIndex: 0,
          hint: '回车也是空白，%d 会跳过它继续等下一个数。',
          explain: '回车（换行符）也是空白字符，%d 读到它就跳过，继续等下一个整数。所以分两行输入和用空格隔开效果一样：a=3、b=7。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出几行、各是什么？',
          code: 'int hp = 42;\nprintf("HP:%d\\n", hp);\nhp = hp + 8;\nprintf("HP:%d\\n", hp);',
          options: ['两行：HP:42 / HP:50', '两行：HP:42 / HP:42', '一行：HP:42', '两行：HP:50 / HP:50'],
          answerIndex: 0,
          hint: '两次 printf 之间，hp 被更新了。',
          explain: '第一次打印 hp 当时的 42；hp = hp + 8 把它更新成 50；第二次打印 50。printf 只是"看一眼"，真正改变量的是中间那行赋值。',
        },
        {
          kind: 'fill',
          prompt: '补全格式符，读入一个单字符：',
          code: 'char c;\nscanf("%___", &c);   /* 读一个字符 */',
          answers: ['c'],
          placeholder: '与 char 配对的字母',
          hint: '和类型同名的那个字母。',
          explain: '%c 读单个字符，正好配 char。全家福：%d 配 int、%lf 配 double（scanf 专用）、%c 配 char——格式符与变量类型严格配对，错了就是未定义行为。',
        },
      ],
    },

    // ============ c1-B Boss：打印码头全线综合 ============
    {
      id: 'c1-B',
      name: '打印码头大测验',
      xp: 100,
      gold: 40,
      boss: true,
      learn: {
        title: 'Boss：打印码头全线复习',
        body: [
          '这一关没有新知识。9 道题把 printf、变量类型、scanf 全部串起来复习，五种题型轮番上阵——答错会当场给解析，放心冲。',
          '全对零提示才能拿到 ★★★ 和完整战利品。码头的汽笛已经拉响，出发！',
        ],
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    printf("胜率:%d%%\\n", 98);\n    return 0;\n}',
          options: ['胜率:98%', '胜率:98%%', '胜率:98', '胜率:%d%'],
          answerIndex: 0,
          hint: '想打印 % 本尊，得用暗号。',
          explain: '% 在格式串里是占位符的开头，想打印 % 本尊要写 %%——两个百分号打一个。所以 %d 填进 98，%% 变成一个 %，最终输出 胜率:98%。这和 \\n 一个道理：特殊符号都得用「转义暗号」表示。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    char c = \'A\' + 2;\n    printf("%c\\n", c);\n    return 0;\n}',
          options: ['C', 'A2', '67', '报错'],
          answerIndex: 0,
          hint: '字符是个小整数，加法照算不误。',
          explain: '\'A\' 在 ASCII 表里编号 65，加 2 得 67，67 号字符是 \'C\'，用 %c 打印就是 C（用 %d 打印会显示 67）。「字符即整数」让 char 能做偏移运算——比如大小写转换就是加减一个固定差值的把戏。',
        },
        {
          kind: 'choice',
          prompt: 'main 最后写 return 0; 是想告诉系统什么？',
          options: ['程序输出了 0 行内容', '向系统报告：程序一切正常地结束了', '让程序跳回开头重新执行', '可有可无，写了反而报错'],
          answerIndex: 1,
          hint: '这个 0 不是数量，是暗号。',
          explain: 'main 的返回类型是 int，return 0; 交还给操作系统的数字叫「退出状态码」：0 按约定表示一切正常，非 0 通常表示出了岔子。顺带一提：C99 起就算漏写这行，main 结束时也会隐式返回 0（实测本机编译无警告、退出码 0），但标准写法都显式带上。',
        },
        {
          kind: 'choice',
          prompt: '下列哪一行能正确声明一个不可修改的小数常量？',
          options: ['const double PI = 3.14;', 'constant double PI = 3.14;', 'final double PI = 3.14;', 'double PI = const 3.14;'],
          answerIndex: 0,
          hint: 'const 是关键字，别发明新词；位置也有讲究。',
          explain: 'C 的关键字是 const，标准写法 const double PI = 3.14;。constant 和 final 是别的语言或自造词，C 编译器不认识；把 const 挪到 3.14 前面更是语法错误。常量名习惯全大写（PI、MAX_HP），一眼认出「封了箱的」。',
        },
        {
          kind: 'fill',
          prompt: '补全占位符，让这行输出 S：',
          code: 'char rank = \'S\';\nprintf("___\\n", rank);   /* → S */',
          answers: ['%c'],
          placeholder: '打印单个字符的占位符',
          hint: 'rank 是 char，别用 %d——那会打印出 83。',
          explain: 'rank 是 char，用 %c 打印字符本身得 S；用 %d 会打印它的 ASCII 编号 83。占位符决定「怎么解读」这箱货——同一箱货，换个标签就换一副面孔。',
        },
        {
          kind: 'fill',
          prompt: '补全格式符，把用户输入的小数读进 double 变量：',
          code: 'double score;\nscanf("___", &score);',
          answers: ['%lf'],
          placeholder: 'scanf 读 double 专用格式符',
          hint: 'printf 打印时用 %f，scanf 这边要多一个字母。',
          explain: 'scanf 读 double 必须写 %lf。写成 %f 的话，scanf 以为目标是个 4 字节的 float，只往 8 字节的 double 里塞一半——未定义行为，数值必坏。而 printf 打印同一个变量用 %f 就行：读和打的规矩不同，千万别混。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行拖回正确顺序——先备货箱，再装货、加工，最后出货：',
          lines: ['int hp;', 'hp = 100;', 'hp = hp - 30;', 'printf("HP:%d\\n", hp);'],
          hint: 'C 要求先声明后使用：先有 hp 这个箱子，才能往里装东西。',
          explain: '顺序是：int hp; 声明货箱；hp = 100 装货；hp = hp - 30 用旧值算出新值再放回（右边先算完 100 - 30 = 70）；printf 出货显示 HP:70。C 是「先声明后使用」的语言，顺序反了编译器就不认识 hp。',
        },
        {
          kind: 'bug',
          prompt: '下面几行里，哪一行会让编译器直接报错？',
          code: ['#include <stdio.h>', 'int main(void) {', '    int 2nd_hp = 5;', '    printf("%d\\n", 2nd_hp);', '    return 0;', '}'],
          answerLine: 2,
          hint: '变量名的第一个字符有讲究。',
          explain: '第 3 行的 2nd_hp：变量名只能由字母、数字、下划线组成，且不能以数字开头。编译器把开头的 2 当成整数常量，nd_hp 成了非法后缀，当场报错（invalid suffix on integer constant）。想表达「二号血条」，写成 hp2 或 hp_2 都行。',
        },
        {
          kind: 'bug',
          prompt: '这段代码编译报错。第一个报错在哪一行？（后面的报错多半是被它连累的）',
          code: ['#include <stdio.h>', 'int main(void) {', '    printf("HP:%d\\n, hp);', '    return 0;', '}'],
          answerLine: 2,
          hint: '有一对引号没成家。',
          explain: '第 3 行的字符串只开了头没闭合，编译器在这行就报 missing terminating " character（缺收尾引号）。后面的 return 0; 整个被卷进了字符串，还会跟着冒出连锁报错。看编译报错要抓第一个，后面的多半是被殃及的池鱼。',
        },
      ],
    },
  ],
}
