import type { RegionDef } from '../course'

/**
 * C 基础 · 区域 2：分岔渡口
 *
 * 每关 6 题、Boss 关 9 题，五种题型混用，每关至少 1 道填空 + 1 道找错。
 * 全部 output 题的运行结果、bug 题的报错行、fill/order 的拼装结果，
 * 均已用本机 gcc -std=c99 -Wall 真机编译运行验算。
 */
export const regionC2: RegionDef = {
  id: 'c2',
  name: '分岔渡口',
  tagline: '每个条件都是一次靠岸选择',
  levels: [
    // ============ c2-1 比较与逻辑运算符、if/else ============
    {
      id: 'c2-1',
      name: '渡口风向标',
      xp: 40,
      gold: 14,
      learn: {
        title: 'if / else：渡口的方向盘',
        body: [
          'C 没有专门的布尔类型那么讲究：任何非 0 值都算「真」，0 算「假」。比较运算符的结果就是 int——成立得 1，不成立得 0。',
          'if (条件) { ... } else { ... }：条件非 0 走 if 支路，否则走 else 支路。C 的条件必须写在圆括号里，用花括号圈地盘——和 Python 的冒号加缩进完全不同。',
          '组合条件用 &&（并且，两边都真才真）、||（或者，一边真就真）、!（取反）。注意是双写的符号：单个 & 和 | 是位运算，完全是两码事。',
          '天坑预警：= 是赋值，== 才是比较。if (hp = 0) 是把 0 赋给 hp，条件恒为假——编译器只给个不起眼的警告，雷埋得极深。',
        ],
        code: 'int hp = 80;\nif (hp > 0 && hp < 100) {    // 两边都真，走这里\n    printf("还能战斗\\n");\n} else {\n    printf("需要撤退\\n");\n}\nprintf("%d\\n", 5 > 3);      // → 1（真）\nprintf("%d\\n", 5 < 3);      // → 0（假）',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int hp = 80;\n    if (hp > 50) {\n        printf("状态良好\\n");\n    } else {\n        printf("需要撤退\\n");\n    }\n    return 0;\n}',
          options: ['状态良好', '需要撤退', '什么都不输出', '编译报错'],
          answerIndex: 0,
          hint: '先把 80 > 50 这笔账算出来。',
          explain: 'hp 是 80，条件 hp > 50 成立（比较结果为 1，即真），走 if 支路输出「状态良好」，else 支路整个跳过。C 的 if 条件必须包在圆括号里，支路用花括号圈起来——这是和 Python 最容易写混的地方。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int hp = 30;\n    int mp = 0;\n    printf("%d\\n", hp > 0 && mp > 0);\n    printf("%d\\n", hp > 0 || mp > 0);\n    return 0;\n}',
          options: ['0 和 1', '1 和 1', '0 和 0', 'True 和 False'],
          answerIndex: 0,
          hint: 'C 没有布尔字面量，比较和逻辑运算的结果就是 1 或 0。',
          explain: 'C 里逻辑运算的结果是 int：真为 1，假为 0，用 %d 直接打印。第一行：mp > 0 为假（mp 是 0），&& 要求两边都真，得 0。第二行：hp > 0 为真，|| 一边真就真，得 1。选项里的 True/False 是 Python 的写法，C 里不存在。',
        },
        {
          kind: 'fill',
          prompt: '补全逻辑运算符，要求「血量充足且蓝量充足」才走 if：',
          code: 'int hp = 80, mp = 30;\nif (hp > 0 ___ mp > 0) {\n    printf("可以施法\\n");\n}',
          answers: ['&&'],
          placeholder: '两个字符的「并且」',
          hint: '「并且」的符号是成双成对的。',
          explain: '&& 表示「并且」，两边都真整体才真：hp > 0 和 mp > 0 都成立，条件为真，输出「可以施法」。千万别写成单个 &——那是位运算符，含义完全不同；虽然碰巧在这种 1 和 1 的场合结果一样，但换个数就露馅，属于埋雷写法。',
        },
        {
          kind: 'bug',
          prompt: '这段代码能通过编译（只有警告），但逻辑是错的。雷埋在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    int hp = 100;', '    if (hp = 0) {', '        printf("还活着\\n");', '    } else {', '        printf("倒下了\\n");', '    }', '    return 0;', '}'],
          answerLine: 3,
          hint: 'if 的括号里混进了一个赋值。',
          explain: '第 4 行 if (hp = 0) 是赋值不是比较：hp 被改成 0，整个条件式的值就是 0，C 里 0 即假——实测运行输出「倒下了」，还顺手把 hp 清了零。比较必须写两个等号：if (hp == 0)。gcc 的警告 suggest parentheses around assignment used as truth value（赋值被当条件用）说的就是这行，看到务必当真。',
        },
        {
          kind: 'choice',
          prompt: '想表达「分数在 60 到 100 之间（含边界）」，哪个条件写法是对的？',
          options: ['score >= 60 && score <= 100', '60 <= score <= 100', 'score >= 60 || score <= 100', 'score = 60..100'],
          answerIndex: 0,
          hint: 'C 不支持数学卷子的连写，得分开比再合起来。',
          explain: '正确写法是两个比较用 && 连起来。60 <= score <= 100 在 C 里是合法表达式但含义全歪：先算 60 <= score 得 0 或 1，再拿这个 0/1 和 100 比——永远成立，防线形同虚设（实测 score 填 1000 或 50 都得 1，gcc 还会警告 X<=Y<=Z do not have their mathematical meaning）。|| 更是南辕北辙，score = 1000 也能过。区间判断必须拆成两个比较。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行拼成一个完整的 if-else：',
          lines: ['if (gold >= 100) {', '    printf("富裕\\n");', '} else {', '    printf("还差一点\\n");', '}'],
          hint: '先 if 的条件和它的支路，收口 } 后面紧跟 else，最后再收一次口。',
          explain: 'C 的 if-else 骨架：if (条件) { 支路 A } else { 支路 B }。每个 { 都要有配对的 } 收口，else 必须紧跟在 if 支路的 } 后面。花括号是 C 圈地的墙——墙里是这条支路的地盘，出墙就归别人管了。',
        },
      ],
    },

    // ============ c2-2 switch-case ============
    {
      id: 'c2-2',
      name: '泊位调度',
      xp: 42,
      gold: 15,
      learn: {
        title: 'switch / case：泊位调度员',
        body: [
          'if-else 链长了容易乱。switch 专管「一个值对号入座」：switch (cmd) 拿着值去找标了同样号码的 case 泊位，找到了就从那里开始执行。',
          'case 只是「入口标签」，不是围栏：命中一个 case 后会一路往下冲，把后面的 case 也执行光——这叫「贯穿（fall-through）」。想停在泊位上，每个 case 末尾必须自己写 break;。',
          '所有 case 都对不上号时，default 兜底——它就是 switch 里的 else，习惯写在最后，同样建议带 break。',
          'case 后面只能跟整数常量（1、2、\'A\' 都行），不能是变量、不能是字符串；比大小、比区间，还是得交给 if。',
        ],
        code: 'int cmd = 2;\nswitch (cmd) {\n    case 1:\n        printf("起航\\n");\n        break;              // 没它就冲进 case 2\n    case 2:\n        printf("抛锚\\n");   // cmd=2 从这儿进\n        break;              // 停住，default 不执行\n    default:\n        printf("无效指令\\n");\n        break;\n}',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int cmd = 2;\n    switch (cmd) {\n        case 1:\n            printf("起航\\n");\n            break;\n        case 2:\n            printf("抛锚\\n");\n            break;\n        default:\n            printf("无效\\n");\n            break;\n    }\n    return 0;\n}',
          options: ['抛锚', '起航', '先抛锚再无效（两行）', '无效'],
          answerIndex: 0,
          hint: 'cmd 是 2，对号入座后遇到 break 就停。',
          explain: 'cmd 为 2，switch 拿它对上 case 2，执行「抛锚」，紧跟着的 break 让程序跳出整个 switch——default 虽然就在下面，也不再执行。一个指令一个泊位，干完就走。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？注意 case 1 末尾少了什么。',
          code: '#include <stdio.h>\nint main(void) {\n    int cmd = 1;\n    switch (cmd) {\n        case 1:\n            printf("起航\\n");\n        case 2:\n            printf("抛锚\\n");\n            break;\n        default:\n            printf("无效\\n");\n    }\n    return 0;\n}',
          options: ['起航（只一行）', '起航 和 抛锚（两行）', '抛锚（只一行）', '编译报错'],
          answerIndex: 1,
          hint: 'case 1 末尾没有 break，会冲到哪里去？',
          explain: 'case 只是入口标签不是围栏：命中 case 1 打印「起航」后，没有 break 拦着，程序一路贯穿冲进 case 2，又打印「抛锚」，直到撞见 break 才跳出整个 switch。这就是「贯穿（fall-through）」——想一个 case 干完就走，末尾必须配 break。',
        },
        {
          kind: 'fill',
          prompt: '补全关键字，让 case 1 干完活就停下，别冲进 case 2：',
          code: 'switch (cmd) {\n    case 1:\n        printf("靠岸\\n");\n        ___;\n    case 2:\n        printf("检修\\n");\n        break;\n}',
          answers: ['break'],
          placeholder: '负责「到此为止」的关键字',
          hint: '五个字母，专门负责「到此为止」。',
          explain: 'break 负责从 switch 里跳出去。没有它，case 1 打印完「靠岸」会贯穿进 case 2 再打印「检修」——明明只下了一个指令，却干了两件事。每个 case 末尾配 break，是 switch 的标准礼仪。',
        },
        {
          kind: 'bug',
          prompt: '这段代码编译报错，错在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    int n = 2;', '    int cmd = 2;', '    switch (cmd) {', '        case n:', '            printf("二号泊位\\n");', '            break;', '    }', '    return 0;', '}'],
          answerLine: 5,
          hint: 'case 后面必须是常数，这是泊位编号的铁律。',
          explain: '第 6 行 case n: 让编译器报错 case label does not reduce to an integer constant——case 后面只能放整数常量（case 2:、case \'A\': 都行），不能放变量。泊位编号必须刻死在码头上，不能等船来了再定。值要运行时才知道？请改用 if-else。',
        },
        {
          kind: 'choice',
          prompt: 'switch 里所有 case 都对不上号时，程序会？',
          options: ['编译报错', '执行 default 分支（如果写了）', '自动执行 case 0', '整个程序卡死'],
          answerIndex: 1,
          hint: '总得有个兜底的泊位。',
          explain: '对不上任何 case 时，有 default 就执行 default（它就是 switch 的 else）；没写 default 就整个 switch 静默跳过——不报错也不吭声，指令被无声吞掉。所以「无效指令」这类兜底提示，习惯交给 default 处理。',
        },
        {
          kind: 'choice',
          prompt: '下列关于 switch 的说法，哪个是对的？',
          options: ['case 后面可以跟字符串 "w"', 'switch 的括号里可以放 double 变量', '不写 default 时，对不上任何 case 的值会被无声跳过', '每个 case 自动互不干扰，break 只是装饰'],
          answerIndex: 2,
          hint: '回想 case 标签的铁律、switch 括号的规矩，和 default 的角色。',
          explain: 'case 只能跟整数常量——case "w": 直接报错（case label does not reduce to an integer constant）；switch 括号里必须是整数类型，放 double 会报 switch quantity not an integer；没写 default 时对不上号的值让整个 switch 静默跳过，不报错但指令被吞，所以关键调度记得留 default。break 绝不是装饰，是防贯穿的闸门。',
        },
      ],
    },

    // ============ c2-3 for / while、break / continue ============
    {
      id: 'c2-3',
      name: '环礁航线',
      xp: 45,
      gold: 16,
      learn: {
        title: 'for / while：绕圈航线',
        body: [
          '循环是「同一段航线绕着飞」。for 最适合数着圈数飞：for (int i = 1; i <= 3; i++) { ... }——括号里三段式：起点、继续条件、每圈收尾动作，用两个分号隔开。',
          'i = i + 1 的惯用缩写是 i++（自增 1），数圈时两者完全等价。圈尾动作的职责是让 i 向终点靠拢，忘了写就是死循环。',
          'while (条件) { ... } 是「只要条件成立就再来一圈」：适合不转满一圈不知道啥时候停的场景。圈里必须有能让条件最终变假的改动，否则永远出不了圈。',
          'break 立刻跳出整条循环（弃船上岸）；continue 只跳过本轮剩下的活，直接进下一圈（跳过这一站）。',
        ],
        code: 'for (int i = 1; i <= 3; i++) {\n    printf("绕第%d圈\\n", i);   // 三行：第1圈 第2圈 第3圈\n}\nint n = 3;\nwhile (n > 0) {\n    printf("%d...\\n", n);      // 3... 2... 1...\n    n--;                       // 删了这行 = 永远绕不完\n}',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    for (int i = 1; i <= 3; i++) {\n        printf("%d\\n", i);\n    }\n    return 0;\n}',
          options: ['1、2、3（各占一行）', '只输出 3', '1、2、3、4（四行）', '永远转下去停不下来'],
          answerIndex: 0,
          hint: 'i 从 1 起步，每圈加 1，i <= 3 不成立就收工。',
          explain: 'for 三段式：i = 1 起步；每圈开头检查 i <= 3，成立就打印 i；圈尾 i++ 加 1。于是依次打印 1、2、3（各占一行）。当 i 变成 4，条件 4 <= 3 不成立，循环干净利落地结束——不会多跑一圈。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int n = 3;\n    while (n > 0) {\n        printf("%d\\n", n);\n        n--;\n    }\n    return 0;\n}',
          options: ['3、2、1（三行）', '3、2、1、0（四行）', '只输出 3', '永远转下去停不下来'],
          answerIndex: 0,
          hint: 'n-- 每圈把 n 减 1，减到 0 条件就假了。',
          explain: 'n 从 3 开始：3 > 0 成立，打印 3，n-- 变 2；再打印 2，变 1；打印 1，变 0。此时 0 > 0 不成立，循环结束。注意 0 不会被打印——while 是先查条件再干活，条件假了根本不进圈。',
        },
        {
          kind: 'fill',
          prompt: '补全圈尾动作，让循环数到 3 后正常停下：',
          code: 'for (int i = 1; i <= 3; ___) {\n    printf("%d\\n", i);\n}',
          answers: ['i++', 'i = i + 1', 'i += 1'],
          placeholder: '让 i 每圈加 1',
          hint: '最短的写法是变量名后跟两个加号。',
          explain: '圈尾动作负责让 i 向终点靠拢：i++（或 i = i + 1、i += 1，三种等价，实测输出完全一样）。要是把这段空着，i 永远是 1，i <= 3 永远成立——死循环，船在原地转到天荒地老。数圈循环三要素：起点、终点条件、每圈的推进。',
        },
        {
          kind: 'bug',
          prompt: '这段程序一运行就永远刷屏停不下来（死循环不报编译错误）。祸根在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    int n = 3;', '    while (n > 0) {', '        printf("%d\\n", n);', '    }', '    return 0;', '}'],
          answerLine: 3,
          hint: '循环体里，有谁在替 n「倒计时」吗？',
          explain: '第 4 行 while (n > 0) 的条件永远成立：圈里没人改 n，n 一直是 3，3 > 0 永远为真，printf 无限刷屏（实测编译毫无警告，跑起来两秒都停不下来）。修法：圈里补一行 n--;，让条件终有变假的一天。死循环不报编译错误，属于「运行时事故」，全靠自己盯住「谁在推进循环」。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    for (int i = 1; i <= 5; i++) {\n        if (i == 4) {\n            break;\n        }\n        printf("%d\\n", i);\n    }\n    return 0;\n}',
          options: ['1、2、3（三行）', '1、2、3、4（四行）', '1 到 5（五行）', '只输出 4'],
          answerIndex: 0,
          hint: 'i 变成 4 的那一刻，break 把整条循环丢了出去。',
          explain: 'i 依次是 1、2、3 时，条件 i == 4 不成立，各打印一行。i 变成 4 的那一圈，if 命中，break 立刻炸出整个 for——不是跳过这一圈，而是整条循环收工，所以 4、5 都不会打印。break 是「弃船」，continue 才是「跳过一站」。',
        },
        {
          kind: 'fill',
          prompt: '补全关键字：3 这一圈不打印，但循环照转：',
          code: 'for (int i = 1; i <= 5; i++) {\n    if (i == 3) {\n        ___;\n    }\n    printf("%d\\n", i);\n}',
          answers: ['continue'],
          placeholder: '「跳过本圈，继续下圈」的关键字',
          hint: '九个字母，跳过这一站，直奔下一站。',
          explain: 'continue 跳过本轮剩余的语句（这一圈的 printf 不执行），直接回到圈尾 i++ 进下一圈——圈数没少，只是 3 这圈哑火，输出 1、2、4、5。对比 break：break 弃船退出整条循环，continue 只是跳过这一圈。',
        },
      ],
    },

    // ============ c2-B Boss：分岔渡口全线综合 ============
    {
      id: 'c2-B',
      name: '分岔渡口大测验',
      xp: 100,
      gold: 40,
      boss: true,
      learn: {
        title: 'Boss：分岔渡口全线复习',
        body: [
          '这一关没有新知识。9 道题覆盖比较逻辑、if/else、switch 和循环，五种题型轮番上阵——答错会当场给解析，放心冲。',
          '全对零提示才能拿到 ★★★ 和完整战利品。渡口的所有泊位都已点亮，出发！',
        ],
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int gold = 55;\n    if (gold >= 100) {\n        printf("富商\\n");\n    } else if (gold >= 50) {\n        printf("小康\\n");\n    } else {\n        printf("穷水手\\n");\n    }\n    return 0;\n}',
          options: ['小康', '富商', '穷水手', '什么都不输出'],
          answerIndex: 0,
          hint: '从上往下找第一个成立的分支。',
          explain: 'gold 为 55：第一关 gold >= 100 不过；第二关 gold >= 50 成立，输出「小康」，整条链到此为止，else 不再看。C 的 else if 本质是「else 里再套一个 if」的缩写——命中第一个成立的分支后，后面的条件一律不再检查。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <stdio.h>\nint main(void) {\n    int cmd = 7;\n    switch (cmd) {\n        case 1:\n            printf("起航\\n");\n            break;\n        case 2:\n            printf("抛锚\\n");\n            break;\n        default:\n            printf("无效指令\\n");\n    }\n    return 0;\n}',
          options: ['无效指令', '起航', '什么都不输出', '编译报错'],
          answerIndex: 0,
          hint: '7 号泊位不存在，看谁兜底。',
          explain: 'cmd 为 7，case 1、case 2 都对不上，default 兜底执行「无效指令」。要是没写 default，这个 switch 就会静默跳过——不报错也不吭声。所以关键指令的调度，务必留一个 default 泊位。',
        },
        {
          kind: 'choice',
          prompt: '已知要打印 1 到 100，哪种写法最合适？',
          options: ['for (int i = 1; i <= 100; i++) { printf("%d\\n", i); }', '手写 100 行 printf', 'while (1) { printf("%d\\n", 1); }', 'if (1 <= 100) { printf("%d\\n", 1); }'],
          answerIndex: 0,
          hint: '起点、终点、步长都明确的活，谁最擅长数圈？',
          explain: '起止明确（1 到 100）、步长固定，for 的三段式就是为这种场景生的：计数器、条件、推进一目了然。while (1) 条件永远是 1，是死循环（除非圈里有 break）；if 只判断一次，打印一行就完了。数着圈干活用 for；不转满一圈不知道啥时候停，才请 while。',
        },
        {
          kind: 'choice',
          prompt: '在循环里，break 和 continue 的区别是？',
          options: ['没区别，都能跳过一圈', 'break 弃船跳出整条循环；continue 只跳过本轮剩下的活，下一圈照转', 'continue 跳出整条循环；break 只跳过一圈', '两个都会终止整个程序'],
          answerIndex: 1,
          hint: '一个是弃船上岸，一个是跳过这一站。',
          explain: 'break 立刻退出整条循环，圈数不再增加；continue 只结束「本轮」，跳到圈尾动作（如 i++）继续下一圈。打个比方：break 是弃船上岸，continue 是跳过这一站直奔下一站。两者只对「最里层」的那条循环生效，套循环时别搞混对象。',
        },
        {
          kind: 'fill',
          prompt: '补全比较运算符，让「血量归零」的判断真正生效：',
          code: 'int hp = 0;\nif (hp ___ 0) {\n    printf("倒下\\n");\n}',
          answers: ['=='],
          placeholder: '两个等号',
          hint: '一个等号是装货，两个等号才是比货。',
          explain: '比较用 ==。写成 if (hp = 0) 会变成赋值：hp 被改成 0，条件式的值是 0 恒为假，「倒下」永远打不出来，而且 hp 被偷偷清零。编译器只给个不起眼的警告——「= 与 == 混用」是 C 新手排名第一的事故。',
        },
        {
          kind: 'fill',
          prompt: '补全继续条件，让循环正好转 5 圈（i 从 1 数到 5）：',
          code: 'for (int i = 1; ___; i++) {\n    printf("第%d圈\\n", i);\n}',
          answers: ['i <= 5', 'i<=5', 'i < 6', 'i<6'],
          placeholder: 'i 和 5（或 6）的比较',
          hint: 'i 从 1 开始，想让第 5 圈也转上，条件得放过 5。',
          explain: 'i 从 1 起步：i <= 5 在 i 为 5 时仍成立，第 5 圈照转，i 变 6 时结束——正好 5 圈（实测打印第 1 圈到第 5 圈）。写成 i < 5 会漏掉第 5 圈只转 4 圈；i < 6 与 i <= 5 完全等价（整数没有中间值），两种都对，但 i <= 5 更贴近「数到 5」的直觉。',
        },
        {
          kind: 'order',
          prompt: '把倒计时流程拖回正确顺序（最后一行要等循环结束后才执行）：',
          lines: ['int n = 3;', 'while (n > 0) {', '    printf("%d\\n", n);', '    n--;', '}', 'printf("发射\\n");'],
          hint: '先备好 n，再问「n > 0 吗」；圈里的活必须包含 n--，否则出不了圈。',
          explain: '顺序：int n = 3 备好倒计时；while (n > 0) 每圈先查条件；圈里打印当前 n 并 n-- 推进；} 收口；最后 printf("发射\\n") 在循环外面——等 n 减到 0、条件为假、跳出循环后才执行，正好接上「3、2、1、发射」。n-- 必须在圈里：放到圈外，条件永远成立，永远喊不出发射。',
        },
        {
          kind: 'bug',
          prompt: '这段代码编译报错，错在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    for (int i = 1 i <= 3; i++) {', '        printf("%d\\n", i);', '    }', '    return 0;', '}'],
          answerLine: 2,
          hint: 'for 括号里的三段，靠什么符号隔开？',
          explain: '第 3 行 for 的括号里漏了第一个分号，编译器在 1 和 i 之间懵了，报 expected \',\' or \';\'（就在这一行）。for (起点; 条件; 推进) 的三段必须用两个分号隔开，一个都不能省——分号是 C 的句子结束符，for 的括号里也不例外。',
        },
        {
          kind: 'bug',
          prompt: '这段代码编译报错，错在哪一行？',
          code: ['#include <stdio.h>', 'int main(void) {', '    for (int i = 1; i <= 3; i++) {', '        printf("%d\\n", i);', '    }', '    printf("绕圈数:%d\\n", i);', '    return 0;', '}'],
          answerLine: 5,
          hint: '在 for 括号里出生的变量，出了循环还活着吗？',
          explain: '第 6 行想打印 i，但 C99 规定：在 for 括号里声明的 i 只属于这个循环，循环一结束就被销毁（实测报 \'i\' undeclared，正指这一行）。出了圈再提 i，编译器不认识。想循环结束后还用圈数，就在 for 之前声明 int i;（这样圈尾的 i++ 推进的就是外面的 i）。',
        },
      ],
    },
  ],
}
