import type { RegionDef } from '../course'

/**
 * 区域 3：数组群岛（C 基础）
 *
 * c3-1 一维数组 → c3-2 字符数组与 '\0' → c3-3 数组综合与越界雷区，
 * Boss 关全线综合。所有 C 代码均已用 gcc -std=c99 -Wall 真机验算。
 */
export const regionC3: RegionDef = {
  id: 'c3',
  name: '数组群岛',
  tagline: '一串宝物拴在同一个名字上',
  levels: [
    // ============ c3-1 一维数组 ============
    {
      id: 'c3-1',
      name: '宝物挂上同一根绳',
      xp: 42,
      gold: 14,
      learn: {
        title: '一维数组：把宝物拴在同一根绳上',
        body: [
          '数组是一排编了号的储物格：int a[5]; 声明 5 个 int 格子。格子的编号叫「下标」，从 0 开始——a[0] 是第 1 格，a[4] 才是最后一格，没有 a[5] 这个格子。',
          '声明时可以直接装填：int a[3] = {7, 8, 9}; 也可以只装一部分，剩下的格子自动补 0：int a[5] = {1, 2}; 则 a[2] 到 a[4] 都是 0。',
          '数组常和 for 搭档巡逻：for (int i = 0; i < 5; i++) 用 a[i] 逐格访问。循环条件写 i < 5 而不是 i <= 5，否则会摸到不存在的第 6 格——那是未定义行为。',
        ],
        code: 'int a[4] = {10, 20, 30, 40};\nprintf("%d\\n", a[0]);   /* → 10（第 1 格） */\na[1] = 99;              /* 单独改某一格 */\nfor (int i = 0; i < 4; i++) {\n    printf("%d ", a[i]);   /* → 10 99 30 40 */\n}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '声明 int a[5]; 之后，下列哪个下标范围是合法的（不会越界）？',
          options: ['a[0] 到 a[4]', 'a[1] 到 a[5]', 'a[0] 到 a[5]', 'a[1] 到 a[4]'],
          answerIndex: 0,
          hint: '下标从 0 起步，最大到「格子数 − 1」。',
          explain: 'int a[5] 有 5 个格子，下标从 0 开始编号，合法范围是 a[0] 到 a[4]。a[5] 是第 6 格，根本不存在，访问它属于越界。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'int a[4] = {2, 4, 6, 8};\nprintf("%d", a[1] + a[3]);',
          options: ['6', '10', '12', '越界报错'],
          answerIndex: 2,
          hint: 'a[1] 不是第 1 格，是第 2 格。',
          explain: '下标从 0 数起：a[1] 是 4，a[3] 是 8，相加得 12。新手常把 a[1] 当成第一个元素 2——记住口诀「下标 = 排位 − 1」。',
        },
        {
          kind: 'fill',
          prompt: '补全下标，让程序打印出数组里的 12：',
          code: 'int a[5] = {3, 6, 9, 12, 15};\nprintf("%d", a[___]);',
          answers: ['3'],
          placeholder: '一个数字下标',
          hint: '12 排在第 4 位，下标从 0 数。',
          explain: '12 是数组里第 4 个元素，下标是 4 − 1 = 3，写 a[3]。数一遍：a[0]=3、a[1]=6、a[2]=9、a[3]=12、a[4]=15。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行排成「声明数组再逐格巡逻」的完整片段：',
          lines: ['int a[3] = {7, 8, 9};', 'for (int i = 0; i < 3; i++) {', '    printf("%d ", a[i]);', '}'],
          hint: '先声明数组，再用 for 从下标 0 走到 2。',
          explain: '先声明并初始化数组 a，然后 for 让 i 依次取 0、1、2，用 a[i] 访问每一格，最后用 } 收尾。条件 i < 3 正好走满 3 格、不越界。',
        },
        {
          kind: 'bug',
          prompt: '下面两行里，哪一行访问了不存在的格子（未定义行为）？',
          code: ['int a[3] = {1, 2, 3};', 'printf("%d", a[3]);'],
          answerLine: 1,
          hint: 'a 只有 3 格，最大下标是多少？',
          explain: '第 2 行的 a[3] 越界了：3 个格子的下标只有 0、1、2。C 编译器不检查越界，程序照样能编译运行，但读到的值无法预料——实测会打出一串随机垃圾数字。这叫「未定义行为」。想拿最后一个元素应该写 a[2]。',
        },
        {
          kind: 'choice',
          prompt: 'int a[4] = {9}; 之后 a[2] 是多少？',
          options: ['9', '0', '随机垃圾值', '编译报错'],
          answerIndex: 1,
          hint: '只装了部分格子时，剩下的格子会被统一安置。',
          explain: '初始化列表给的值不够时，C 标准规定剩下的元素全部自动补 0：a[0] 是 9，a[1] 到 a[3] 都是 0，所以 a[2] 是 0。这是标准明文规定的，不是运气。',
        },
      ],
    },

    // ============ c3-2 字符数组与 '\0' ============
    {
      id: 'c3-2',
      name: '会打结的字符卷轴',
      xp: 44,
      gold: 15,
      learn: {
        title: "字符数组：末尾拴着 '\\0' 的卷轴",
        body: [
          'C 没有真正的字符串类型，字符串就是字符数组：char s[] = "abc"; 装了 4 个字符——a、b、c，外加看不见的结束标记 \'\\0\'。方括号留空时，长度自动数好。',
          "'\\0'（空字符）是卷轴末尾的「封蜡」：读到它就知道字符串到头了。所以装下 \"abc\" 需要 4 个格子；strlen(s) 数出的长度是 3，不把 '\\0' 算进去。",
          'sizeof(s) 问的是数组总共占几个字节（4），strlen(s) 问的是卷轴正文写了几个字（3）——两个问题，两种答案，千万别混。',
        ],
        code: 'char s[] = "abc";\nprintf("%d\\n", (int)sizeof(s));   /* → 4（含 \\0） */\nprintf("%d\\n", (int)strlen(s));   /* → 3（不含 \\0） */\nprintf("%c\\n", s[0]);             /* → a */',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'char s[] = "hi"; 这个数组总共占了几个格子？',
          options: ['2 个，就两个字母', "3 个，多出一个看不见的 '\\0'", '4 个，C 会自动凑整', '不确定，看运气'],
          answerIndex: 1,
          hint: '字符串末尾还拴着一个结束标记。',
          explain: "\"hi\" 的真实内容是 'h'、'i'、'\\0' 三个字符——C 会自动在字符串字面量末尾补上结束标记 '\\0'，它也占一个格子。所以这个数组一共 3 个格子。",
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: '#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char s[] = "game";\n    printf("%d", (int)strlen(s));\n    return 0;\n}',
          options: ['4', '5', '8', '0'],
          answerIndex: 0,
          hint: "strlen 数的是正文字符数，不含结尾的 '\\0'。",
          explain: "\"game\" 有 4 个字母，strlen 返回 4——它数到 '\\0' 为止，但不把 '\\0' 算进去。strlen 返回的是 size_t 类型，用 (int) 转一下再配合 %d 打印最稳妥。",
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'char s[] = "abc";\nprintf("%d %d", (int)sizeof(s), (int)strlen(s));',
          options: ['3 3', '4 3', '3 4', '4 4'],
          answerIndex: 1,
          hint: 'sizeof 数格子，strlen 数正文。',
          explain: "sizeof(s) 是数组总共的格子数 4（3 个字母 + '\\0'），strlen(s) 是写到封蜡前的正文长度 3。分工记牢：sizeof 管整卷卷轴多长，strlen 管正文写了几个字。",
        },
        {
          kind: 'fill',
          prompt: '补全下标，打印卷轴上的最后一个字母 w：',
          code: 'char s[] = "wow";\nprintf("%c", s[___]);',
          answers: ['2'],
          placeholder: '一个数字下标',
          hint: '三个字母的最后一个，下标是几？',
          explain: "格子里是 s[0]='w'、s[1]='o'、s[2]='w'，最后一个字母的下标是 2（长度 3 减 1）。%c 用来打印单个字符。",
        },
        {
          kind: 'bug',
          prompt: '下面两行里，哪一行会直接编译报错？',
          code: ['char name[5];', 'name = "tom";'],
          answerLine: 1,
          hint: '数组名不是普通变量，不能被整体赋值。',
          explain: '第 2 行想给数组「整体改名」，但数组名不是可修改的变量，C 不允许对数组赋值，gcc 实测报错：assignment to expression with array type。想装字符串，要么声明时直接初始化 char name[5] = "tom";，要么用 strcpy 逐格复制。',
        },
        {
          kind: 'order',
          prompt: "把打乱的行排成「读到结束标记 '\\0' 才停」的巡逻循环：",
          lines: ['char s[] = "cat";', "for (int i = 0; s[i] != '\\0'; i++) {", '    printf("%c", s[i]);', '}'],
          hint: "先有卷轴，再从下标 0 出发，撞见 '\\0' 就停。",
          explain: "先声明字符串 s，然后 for 从 i = 0 出发：只要 s[i] 不是结束标记 '\\0'，就打印这一格并 i++。这正是 strlen 内部的干活方式——读到封蜡就收工。",
        },
      ],
    },

    // ============ c3-3 数组综合 + 越界概念 ============
    {
      id: 'c3-3',
      name: '宝图总计与越界雷区',
      xp: 45,
      gold: 16,
      learn: {
        title: '数组武艺：求和、打擂台与逆序',
        body: [
          '求和：先立一块空牌子 sum = 0，for 循环里 sum += a[i] 逐格累加，走完一圈总和就清点完毕。',
          "找最大值用「打擂台」：让 max 先站上擂台（max = a[0]），后面的元素挨个挑战，谁比 max 大谁上台。从 a[1] 开始挑战就够了，a[0] 自己跟自己比没有意义。",
          '逆序：把第 i 格和倒数第 i 格两两交换，循环到中点就停（i < 长度的一半），否则换过去又换回来等于白干。另外记住：越界访问数组是未定义行为——编译能过，但可能读到垃圾值、写坏别的变量甚至崩溃。',
        ],
        code: 'int a[4] = {5, 2, 8, 1};\nint sum = 0, max = a[0];\nfor (int i = 0; i < 4; i++) {\n    sum += a[i];\n    if (a[i] > max) max = a[i];\n}\nprintf("%d %d\\n", sum, max);   /* → 16 8 */',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段「清点宝物」代码运行后输出什么？',
          code: 'int a[4] = {2, 5, 1, 8};\nint sum = 0;\nfor (int i = 0; i < 4; i++) {\n    sum += a[i];\n}\nprintf("%d", sum);',
          options: ['8', '16', '15', '10'],
          answerIndex: 1,
          hint: 'sum 从 0 起步，把 4 格挨个加上去。',
          explain: '循环把 a[0] 到 a[3] 逐格累加：2 + 5 + 1 + 8 = 16。注意下标最大只到 3，条件 i < 4 保证不摸到不存在的格子。',
        },
        {
          kind: 'output',
          prompt: '这段「打擂台找最大值」代码运行后输出什么？',
          code: 'int a[5] = {7, 3, 9, 2, 5};\nint max = a[0];\nfor (int i = 1; i < 5; i++) {\n    if (a[i] > max) {\n        max = a[i];\n    }\n}\nprintf("%d", max);',
          options: ['7', '5', '9', '26'],
          answerIndex: 2,
          hint: 'max 站上擂台后，谁比它大谁上台。',
          explain: 'max 先取 a[0] 的 7；接着 3、9、2、5 依次挑战，9 比 7 大，max 换成 9。循环结束 max 就是全场最大的 9。把 sum 的套路和 if 比大小拼在一起，就是最常用的数组武艺组合。',
        },
        {
          kind: 'fill',
          prompt: '补全循环边界，让 {1, 2, 3, 4} 恰好逆序成 {4, 3, 2, 1}：',
          code: 'int a[4] = {1, 2, 3, 4};\nint tmp;\nfor (int i = 0; i < ___; i++) {\n    tmp = a[i];\n    a[i] = a[3 - i];\n    a[3 - i] = tmp;\n}',
          answers: ['2'],
          placeholder: '一个数字',
          hint: '首尾配对交换，到中点就该收手。',
          explain: '4 个元素只需要交换 2 对：a[0]↔a[3]、a[1]↔a[2]，所以 i < 2。若写成 i < 4，前两对换完又被换回去，数组反而变回原样——逆序循环只走到中点。',
        },
        {
          kind: 'bug',
          prompt: '这段求和代码有一处会摸到不存在的格子（未定义行为），问题出在哪一行？',
          code: ['int a[4] = {1, 2, 3, 4};', 'int sum = 0;', 'for (int i = 0; i <= 4; i++) {', '    sum += a[i];', '}'],
          answerLine: 2,
          hint: '循环条件多算了一格。',
          explain: '第 3 行的条件 i <= 4 让 i 一路走到 4，而数组合法下标只有 0 到 3，最后一轮 sum += a[4] 越界。实测能编译运行，但会累加进一个随机垃圾值。这是未定义行为，正确写法是 i < 4。',
        },
        {
          kind: 'choice',
          prompt: '关于「数组越界」，下列说法正确的是？',
          options: [
            'C 会自动把越界的格子当成 0',
            '越界不一定会立刻崩溃，但行为不可预料，属于未定义行为',
            '只要程序能编译通过，越界就没有关系',
            '越界一定会让程序马上报错退出',
          ],
          answerIndex: 1,
          hint: '未定义行为的可怕之处恰恰是「看起来没事」。',
          explain: 'C 编译器不检查越界。越界读可能拿到垃圾值，越界写可能悄悄破坏旁边的变量——有时程序照常跑，有时莫名崩溃，标准对它不做任何承诺。别指望编译器或运行时替你把关，循环边界要自己写对。',
        },
      ],
    },

    // ============ c3-B Boss：数组群岛大测验 ============
    {
      id: 'c3-B',
      name: '数组群岛大测验',
      xp: 100,
      gold: 40,
      boss: true,
      learn: {
        title: 'Boss：数组群岛全线复习',
        body: [
          "这一关没有新知识，9 道题覆盖三个小关：一维数组与下标、字符数组与 '\\0'、求和/打擂台/逆序，外加越界这片雷区。答错会当场给解析，放心冲。",
          '全对零提示才能拿到 ★★★ 和完整战利品。群岛的宝图已全部点亮，出发！',
        ],
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'int a[6] = {1, 2, 3};\nprintf("%d", a[5]);',
          options: ['3', '0', '随机垃圾值', '编译报错'],
          answerIndex: 1,
          hint: '初始化列表比格子数短时，C 有明文规定。',
          explain: '初始化列表只给了 3 个值，C 标准规定剩下的格子全部自动补 0，所以 a[3]、a[4]、a[5] 都是 0，输出 0。注意这和「越界读到垃圾值」不同——a[5] 在 6 个格子之内，是合法访问。',
        },
        {
          kind: 'output',
          prompt: '这段「隔格巡逻」代码运行后输出什么？',
          code: 'int a[5] = {10, 20, 30, 40, 50};\nint s = 0;\nfor (int i = 0; i < 5; i += 2) {\n    s += a[i];\n}\nprintf("%d", s);',
          options: ['60', '90', '100', '150'],
          answerIndex: 1,
          hint: 'i 依次取 0、2、4。',
          explain: 'i += 2 让循环只踩下标 0、2、4 三格：10 + 30 + 50 = 90。下标 1、3 里的 20 和 40 从头到尾没被访问。',
        },
        {
          kind: 'fill',
          prompt: '补全打擂台的条件，找出数组里的最大值：',
          code: 'int a[4] = {5, 10, 15, 20};\nint max = a[0];\nfor (int i = 1; i < 4; i++) {\n    if (a[i] > ___) {\n        max = a[i];\n    }\n}\nprintf("%d", max);   /* 输出 20 */',
          answers: ['max'],
          placeholder: '挑战者要和谁比大小？',
          hint: '挑战者要和站在擂台上的那位比。',
          explain: '打擂台的逻辑是「当前元素和擂主 max 比较」，挑战者更大才换人。填 max 后循环正确找出最大值 20。和 a[i] 自己比、或者和循环变量比都乱套了。',
        },
        {
          kind: 'bug',
          prompt: '下面三行里，哪一行会直接编译报错？',
          code: ['int a[3] = {1, 2, 3};', 'int b[3];', 'b = a;'],
          answerLine: 2,
          hint: '数组名不能整体赋值。',
          explain: '第 3 行想把整个数组一口气交给 b，但 C 不允许对数组赋值（数组名不是可修改的变量），gcc 实测报错：assignment to expression with array type。要复制内容得用循环逐格搬，或者用 memcpy。',
        },
        {
          kind: 'order',
          prompt: 'a 已声明为 int a[4] = {4, 1, 3, 2}; 把打乱的行排成完整的「打擂台找最大值」片段：',
          lines: ['int max = a[0];', 'for (int i = 1; i < 4; i++) {', '    if (a[i] > max) {', '        max = a[i];', '    }', '}'],
          hint: '擂主先登台，再从 a[1] 开始逐个挑战。',
          explain: '正确顺序：先让 max = a[0] 登台；for 从 i = 1 扫到 i = 3；每格用 if (a[i] > max) 挑战，更大就换擂主；最后两个 } 依次收起 if 和 for。走完后 max 是 4。',
        },
        {
          kind: 'choice',
          prompt: "关于 '\\0'，下列说法正确的是？",
          options: [
            "strlen(s) 统计的结果包含 '\\0'",
            'char s[] = "abc" 只需要 3 个格子',
            "'\\0' 是字符串的结束标记，占 1 个字节",
            "没有 '\\0' 结尾的字符数组一定无法逐格访问",
          ],
          answerIndex: 2,
          hint: '它是卷轴末尾的封蜡。',
          explain: "'\\0' 是数值为 0 的字符，C 用它标记字符串到头了，占 1 个字节。strlen 不统计它，\"abc\" 因此需要 4 个格子。逐字符访问 s[i] 靠的只是下标，和有没有 '\\0' 无关；但缺了 '\\0' 的数组绝不能交给 strlen 或 %s——它们会一路读到失控。",
        },
        {
          kind: 'output',
          prompt: '这段逆序代码运行后输出什么？',
          code: 'int a[4] = {1, 2, 3, 4};\nint tmp;\nfor (int i = 0; i < 2; i++) {\n    tmp = a[i];\n    a[i] = a[3 - i];\n    a[3 - i] = tmp;\n}\nprintf("%d %d %d %d", a[0], a[1], a[2], a[3]);',
          options: ['1 2 3 4', '4 3 2 1', '2 1 4 3', '4 3 1 2'],
          answerIndex: 1,
          hint: 'i = 0 换首尾，i = 1 换中间两个。',
          explain: 'i = 0 时 a[0] 和 a[3] 交换，变成 4 2 3 1；i = 1 时 a[1] 和 a[2] 交换，变成 4 3 2 1。循环到中点收手，正好完成逆序。',
        },
        {
          kind: 'fill',
          prompt: '补全 while 的条件，不用 strlen 也数出卷轴长度（len 最终为 3）：',
          code: 'char pwd[] = "gem";\nint len = 0;\nwhile (pwd[len] != ___) {\n    len++;\n}\nprintf("%d", len);   /* 输出 3 */',
          answers: ["'\\0'", '0'],
          placeholder: "读到哪个字符就停？（可写 '\\0' 或它的值）",
          hint: "字符串的尽头拴着哪个字符？",
          explain: "字符串末尾有结束标记 '\\0'，条件 pwd[len] != '\\0' 让循环正好停在封蜡前，len 数出 3——这正是 strlen 的原理。填数字 0 也对：'\\0' 的值就是 0。",
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'int a[3] = {8, 8, 8};\na[1] += 2;\na[2] = a[0] + a[1];\nprintf("%d", a[1] + a[2]);',
          options: ['18', '26', '28', '30'],
          answerIndex: 2,
          hint: '一格一格算清楚再相加。',
          explain: 'a[1] += 2 后变成 10；a[2] = a[0] + a[1] = 8 + 10 = 18；最后打印 a[1] + a[2] = 10 + 18 = 28。数组元素既能当右值读，也能当左值写。',
        },
      ],
    },
  ],
}
