import type { RegionDef } from '../course'

/** 区域 5：字典城（全课程毕业区域） */
export const region5: RegionDef = {
  id: '5',
  name: '字典城',
  tagline: '有名字的宝箱城',
  levels: [
    {
      id: '5-1',
      name: '有名字的宝箱',
      xp: 45,
      gold: 15,
      learn: {
        title: '字典：有名字的宝箱城',
        body: [
          '字典（dict）就像一排带名牌的宝箱：每个宝箱有「键」（名牌）和「值」（里面的东西）。写法是 {键: 值}。',
          '取值不按位置，而是按名牌：hero["名字"] 拿到键「名字」对应的值，跟它排第几个无关。',
          '键必须唯一：同一个键后写的值会覆盖先写的。从空字典 {} 起步，用赋值 chest["宝石"] = 3 就能往里添加新的键值对。',
        ],
        code: 'hero = {"名字": "勇者", "血量": 100}\nhero["名字"]          # → "勇者"（按键取值，不看位置）\nhero["血量"] = 80     # 已有的键 = 改值\nhero["金币"] = 50     # 没有的键 = 新增一对\n# 同名键后写覆盖先写：\n{"a": 1, "a": 2}      # → {"a": 2}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '字典和列表最大的区别是？',
          options: ['字典按位置取值，列表按键取值', '字典按键取值，列表按位置取值', '两者都按位置取值', '两者都按键取值'],
          answerIndex: 1,
          hint: '列表用序号 0/1/2，字典用「名牌」键。',
          explain: '列表靠位置（索引 0、1、2…）取值；字典靠键（名牌）取值，跟存放顺序无关。这是两种结构最根本的区别。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'hero = {"名字": "勇者", "血量": 100}\nhero["血量"]',
          options: ['100', '"勇者"', '"血量"', '报错'],
          answerIndex: 0,
          hint: '中括号里填的是「键」，不是序号。',
          explain: 'hero["血量"] 按键「血量」取值，得到 100。字典不按位置取，所以不存在「第几个」的问题。',
        },
        {
          kind: 'choice',
          prompt: '执行后 d 的值是？',
          code: 'd = {"a": 1, "a": 2}',
          options: ['{"a": 1, "a": 2}', '{"a": 2}', '{"a": 1}', '报错'],
          answerIndex: 1,
          hint: '同一个键不能出现两次。',
          explain: '字典的键必须唯一，后写的值会覆盖先写的，所以只剩 {"a": 2}。这跟列表不同——列表允许重复元素。',
        },
        {
          kind: 'fill',
          prompt: '补全代码，往空字典里添加一对键值（填一个符号）：',
          code: 'chest = {}\nchest["宝石"] ___ 3   # 现在 chest 是 {"宝石": 3}',
          answers: ['='],
          placeholder: '赋值符号',
          hint: '给字典添加新键值对，用的符号和给变量赋值一样。',
          explain: '对不存在的键做赋值 chest["宝石"] = 3，就是新增一对键值；对已存在的键赋值则是修改。这个等号 = 和变量赋值是同一个符号。',
        },
        {
          kind: 'choice',
          prompt: '下面哪种写法能创建一个空字典，之后再往里添加内容？',
          options: ['{}', '[]', '()', 'set()'],
          answerIndex: 0,
          hint: '字典用花括号。',
          explain: '{} 是空字典。[] 是空列表，() 是空元组，set() 是空集合——四种都不同，别混了。',
        },
        {
          kind: 'order',
          prompt: '把这三行排成能顺利执行的顺序：',
          lines: ['chest = {}', 'chest["金币"] = 10', 'chest["金币"]'],
          hint: '得先有字典，才能往里放东西、再取出来。',
          explain: '先建空字典，再给一个新键赋值（新增），最后才能取这个键的值。颠倒顺序的话，后面两行根本找不到对象。',
        },
      ],
    },
    {
      id: '5-2',
      name: '城门守卫',
      xp: 48,
      gold: 16,
      learn: {
        title: '字典守卫术：get / in / del',
        body: [
          '直接用 hero["金币"] 取值时，如果键不存在，Python 会当场翻脸——抛出 KeyError。守卫不让没名牌的人进城。',
          '安全的办法是 hero.get("金币", 0)：键存在就返回对应值，不存在就返回你给的默认值 0，绝不报错。',
          '用 "金币" in hero 可以先查键在不在（返回 True/False）；del hero["金币"] 能删掉一对键值；赋值 hero["金币"] = x 对已有键是改、对新键是增。',
        ],
        code: 'hero = {"名字": "勇者"}\nhero["名字"]          # → "勇者"\nhero["金币"]          # → KeyError！没有这个键\nhero.get("金币", 0)   # → 0（键不存在，用默认值）\n"金币" in hero        # → False\nhero["金币"] = 50     # 没有=新增\ndel hero["金币"]      # 删除这对键值',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'hero = {"名字": "勇者"}\nhero["金币"]',
          options: ['None', '0', '报错：KeyError', '"勇者"'],
          answerIndex: 2,
          hint: '键不存在时，方括号取值不会悄悄返回 0。',
          explain: '用方括号取一个不存在的键，Python 直接抛 KeyError，程序会中断。这正是 get() 存在的理由。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'hero = {"名字": "勇者"}\nhero.get("金币", 0)',
          options: ['"勇者"', '0', 'None', '报错'],
          answerIndex: 1,
          hint: 'get 的第二个参数是「找不到时怎么办」。',
          explain: 'get("金币", 0) 找不到键「金币」，就用默认值 0 顶上，绝不报错。这正是它比方括号安全的地方。',
        },
        {
          kind: 'choice',
          prompt: '执行后 result 的值是？',
          code: 'hero = {"血量": 100}\nresult = "血量" in hero',
          options: ['True', 'False', '100', '报错'],
          answerIndex: 0,
          hint: 'in 查的是「键在不在」，不是值。',
          explain: '"血量" in hero 检查键「血量」是否存在，返回 True。in 查的是键，不是值，也不是位置。',
        },
        {
          kind: 'choice',
          prompt: 'hero = {"名字": "勇者"}，hero.get("金币") 的结果是？',
          options: ['0', '""（空字符串）', 'None', '报错'],
          answerIndex: 2,
          hint: '不写第二个参数时，get 默认返回什么？',
          explain: 'get 只传一个参数时，找不到键就返回 None（不报错，但也不是 0）。想拿到 0 这种具体默认值，必须显式写第二个参数。',
        },
        {
          kind: 'fill',
          prompt: '补全代码，删掉字典里的一对键值（填一个关键字）：',
          code: '___ hero["血量"]   # 删掉这对键值',
          answers: ['del'],
          placeholder: '删除关键字',
          hint: '三个字母，意为 delete（删除）。',
          explain: 'del hero["血量"] 删除键「血量」及其值。删完之后再取这个键就会 KeyError。del 也能删变量，是个通用删除关键字。',
        },
        {
          kind: 'choice',
          prompt: '执行后 chest 的内容是？',
          code: 'chest = {"宝石": 1}\nchest["宝石"] = 5\nchest["金币"] = 10',
          options: ['{"宝石": 5, "金币": 10}', '{"宝石": 1, "金币": 10}', '{"宝石": 5}', '报错'],
          answerIndex: 0,
          hint: '已有的键赋值=改；没有的键赋值=增。',
          explain: 'chest["宝石"]=5 改了已有键（1→5）；chest["金币"]=10 新增了一对。所以最终是 {"宝石": 5, "金币": 10}。一个等号同时承担「改」和「增」两种角色，取决于键在不在。',
        },
      ],
    },
    {
      id: '5-3',
      name: '咒语工坊',
      xp: 50,
      gold: 18,
      learn: {
        title: '函数：把咒语封进卷轴',
        body: [
          '函数（function）就像封进卷轴的咒语：定义一次，之后随时念出来用。用 def 定义，括号里写参数（咒语需要的材料），冒号后缩进的几行是咒语正文。',
          'return 把结果送出函数；如果不写 return，函数会默默返回 None。函数「先定义、后调用」——调用时写函数名加括号。',
          '参数是函数内部的临时变量：调用时把值传进去，函数用完就丢，不影响外面的同名变量。',
        ],
        code: 'def greet(name):\n    return "你好，" + name\n\ngreet("勇者")      # → "你好，勇者"\n\ndef show_hp():\n    print("血量：100")   # 没有 return\n\nresult = show_hp()   # → 打印「血量：100」，result 是 None',
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段代码运行后，greet("勇者") 的返回值是？',
          code: 'def greet(name):\n    return "你好，" + name\n\ngreet("勇者")',
          options: ['"你好，name"', '"你好，勇者"', 'None', '报错'],
          answerIndex: 1,
          hint: '参数 name 在调用时被换成了什么？',
          explain: '调用 greet("勇者") 时，参数 name 接收到 "勇者"，return 把 "你好，" + "勇者" 送出来，得 "你好，勇者"。',
        },
        {
          kind: 'choice',
          prompt: '执行后 result 的值是？',
          code: 'def show_hp():\n    print("血量：100")\n\nresult = show_hp()',
          options: ['"血量：100"', '100', 'None', '报错'],
          answerIndex: 2,
          hint: '函数没有写 return 会怎样？',
          explain: 'show_hp 只 print 不 return，所以返回值是 None。print 把字打到屏幕上，但函数本身「没给出答案」——result 拿到的是 None。',
        },
        {
          kind: 'choice',
          prompt: '下面这段代码会怎样？',
          code: 'say_hi("勇者")\n\ndef say_hi(name):\n    print("hi " + name)',
          options: ['正常输出「hi 勇者」', '报错：say_hi 未定义', '输出空行', '报错：参数错误'],
          answerIndex: 1,
          hint: 'Python 从上往下执行，定义还没轮到。',
          explain: 'Python 从上往下逐行执行，调用 say_hi 时它的 def 还没轮到，所以名字还不存在，抛 NameError。函数必须先定义、后调用，顺序不能颠倒。',
        },
        {
          kind: 'fill',
          prompt: '补全代码，定义一个函数（填关键字）：',
          code: '___ greet(name):\n    return "你好，" + name',
          answers: ['def'],
          placeholder: '定义函数的关键字',
          hint: '三个字母，是 define（定义）的缩写。',
          explain: 'def 是定义函数的关键字，后面跟函数名和参数列表，冒号结尾，下一行缩进写函数体。漏了 def 就不是函数定义。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后，add(3, 5) 的返回值是？',
          code: 'def add(a, b):\n    return a + b\n\nadd(3, 5)',
          options: ['8', '35', 'None', '报错'],
          answerIndex: 0,
          hint: '参数按位置对应：a 接 3，b 接 5。',
          explain: '调用 add(3, 5) 时，a=3、b=5（按位置对应），return 3+5=8。多个参数按顺序一一对应。',
        },
        {
          kind: 'order',
          prompt: '把这三行排成能顺利执行的顺序：',
          lines: ['def greet(name):', '    return "你好，" + name', 'greet("勇者")'],
          hint: 'def 那行在前，缩进的函数体紧跟其后，最后才是调用。',
          explain: '先写 def 头、再写缩进的函数体（两者一起构成定义），最后才能调用。调用放在定义之前会 NameError。',
        },
        {
          kind: 'output',
          prompt: 'f(3) 的返回值是？',
          code: 'def f(x, y=10):\n    return x + y\n\nf(3)',
          options: ['3', '13', '10', '报错'],
          answerIndex: 1,
          hint: '没传的参数会用什么？',
          explain: 'y 没传，自动用默认值 10，所以 f(3) = 3 + 10 = 13。默认参数让函数调用更灵活——常用值可以不传。',
        },
        {
          kind: 'output',
          prompt: '执行后 print(g()) 和 print(x) 分别输出什么？',
          code: 'x = 5\n\ndef g():\n    x = 10\n    return x\n\nprint(g())\nprint(x)',
          options: ['10 / 10', '5 / 5', '10 / 5', '5 / 10'],
          answerIndex: 2,
          hint: '函数内的 x 和外面的 x 是两个变量。',
          explain: '函数 g 里 x=10 是个全新的局部变量，和外面的 x=5 是两个东西。g() 内部返回 10，但外面的 x 仍是 5。函数内赋值不污染外层——这是函数作用域的核心规则。',
        },
        {
          kind: 'output',
          prompt: '执行后 b 的值是？',
          code: 'def get():\n    return 1, 2, 3\n\na, b, c = get()\nb',
          options: ['1', '2', '3', '(1, 2, 3)'],
          answerIndex: 1,
          hint: 'return 多个值其实是返回一个元组，左边按位置拆开。',
          explain: 'return 1, 2, 3 实际是 return (1, 2, 3)。a, b, c = get() 按位置拆包，b 拿到第二个元素 2。多返回值是 Python 的语法糖。',
        },
      ],
    },
    {
      id: '5-4',
      name: '错误避风港',
      xp: 50,
      gold: 18,
      learn: {
        title: '异常处理：try / except / finally',
        body: [
          '出错时 Python 抛异常（Exception），程序当场中断。try/except 可以「兜住」异常，让程序继续跑——写健壮代码的标配。',
          'try 块放可能出错的代码；except 错误类型 后跟处理代码——错误类型不匹配则不兜，异常照常上抛。',
          'finally 块不管有没有出错都会执行——常用来收尾（关文件、释放资源）。',
        ],
        code: 'try:\n    x = 1 / 0             # 会抛 ZeroDivisionError\nexcept ZeroDivisionError:\n    print("抓住除零")     # 类型匹配才兜住\nexcept ValueError:\n    pass                    # int("abc") 是 ValueError,不兜 0 除\nexcept:\n    print("兜底")         # 不写类型,什么都接',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'try/except 的主要作用是？',
          options: [
            '加速代码执行',
            '把可能出错的代码「兜」起来,出错时不中断程序',
            '代替 if/else 做判断',
            '让 print 输出更快',
          ],
          answerIndex: 1,
          hint: '想想 except 这个词的意思。',
          explain: 'try/except 的作用是「兜住」异常:try 块出错时,except 块接管处理,程序不会当场中断。可以指定异常类型,只兜匹配的错误。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'try:\n    print("OK")\nexcept:\n    print("NO")',
          options: ['OK', 'NO', 'OK 和 NO 都打印', '报错'],
          answerIndex: 0,
          hint: 'try 块没出错,except 会执行吗？',
          explain: 'try 块顺利跑完没出错,except 块就不执行——只打印 "OK"。except 是出错时的「备用方案」,平时不跑。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("caught")\nprint("end")',
          options: ['caught 和 end', 'end', '报错 ZeroDivisionError', 'caught'],
          answerIndex: 0,
          hint: '1/0 会抛什么异常？except 抓住了之后呢？',
          explain: '1/0 抛 ZeroDivisionError,被 except 抓住,打印 "caught"。try 块「安全结束」后继续往下跑,再打印 "end"。',
        },
        {
          kind: 'fill',
          prompt: '补全代码,填异常处理的关键字:',
          code: 'try:\n    print(int("abc"))\n___ ValueError:\n    print("v")',
          answers: ['except'],
          placeholder: '兜异常的关键字',
          hint: '六个字母,是「除……之外」的意思。',
          explain: 'except 关键字后跟异常类型,定义「这种错误出现时该怎么办」。int("abc") 抛 ValueError,被 except ValueError 抓住。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['try:', '    x = 1 / 0', 'except ValueError:', '    print("v")', 'print("done")'],
          answerLine: 1,
          hint: 'except 后面写的错误类型对得上吗？',
          explain: '1/0 抛的是 ZeroDivisionError,但 except 写的是 ValueError——类型不匹配,except 不兜,异常照常上抛。第 2 行 x = 1/0 是出错源头。',
        },
      ],
    },
    {
      id: '5-B',
      name: '字典城大测验',
      xp: 120,
      gold: 50,
      boss: true,
      learn: {
        title: 'Boss 来了：全课程毕业测验',
        body: [
          '这是「代码群岛」的最终关卡！10 道题覆盖变量、字符串、分支、循环、列表、字典、函数——整段旅程的精华浓缩于此。',
          '答错会当场给解析，别怕试错。全对零提示才能拿到 ★★★ 和完整战利品。整理行囊，出发吧！',
        ],
      },
      questions: [
        {
          kind: 'choice',
          prompt: '执行后 hp 的值是？',
          code: 'hp = 100\nhp = hp - 25',
          options: ['75', '100', '-25', '报错'],
          answerIndex: 0,
          hint: '右边先算，再存回左边。',
          explain: '右边 100-25=75 算完，再存回 hp。变量的「更新」永远先算右边，这是贯穿全课程的基本功。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: '"勇" + "者" * 2',
          options: ['"勇者者"', '"勇者勇者"', '"勇勇者者"', '报错'],
          answerIndex: 0,
          hint: '乘法优先级高于加法，先算乘。',
          explain: '* 优先级高于 +：先算 "者"*2="者者"，再 "勇"+"者者"="勇者者"。想得到「勇者勇者」要加括号：("勇"+"者")*2。',
        },
        {
          kind: 'choice',
          prompt: '执行后 msg 的值是？',
          code: 'gold = 50\nif gold >= 100:\n    msg = "富有"\nelse:\n    msg = "贫穷"',
          options: ['"富有"', '"贫穷"', 'None', '报错'],
          answerIndex: 1,
          hint: 'gold 够不够 100？',
          explain: 'gold=50 不满足 >=100，走 else 分支，msg="贫穷"。if/else 二选一，条件为假就执行 else。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后 total 的值是？',
          code: 'total = 0\nfor i in range(3):\n    total = total + i\ntotal',
          options: ['3', '6', '0', '报错'],
          answerIndex: 0,
          hint: 'range(3) 会给出哪些数？',
          explain: 'range(3) 依次给出 0、1、2，total=0+0+1+2=3。range(N) 从 0 数到 N-1，不含 N。',
        },
        {
          kind: 'choice',
          prompt: '执行后 bag[1] 的值是？',
          code: 'bag = ["剑", "盾", "药"]\nbag.append("弓")',
          options: ['"盾"', '"剑"', '"弓"', '"药"'],
          answerIndex: 0,
          hint: '列表从 0 开始数，append 加在最后。',
          explain: 'bag 从 0 开始：bag[0]="剑"、bag[1]="盾"、bag[2]="药"。append 把"弓"加到末尾，不影响已有元素的位置。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'hero = {"名字": "勇者", "血量": 100}\nhero["血量"]',
          options: ['100', '"勇者"', '"血量"', '报错'],
          answerIndex: 0,
          hint: '字典按「键」取值。',
          explain: 'hero["血量"] 按键取值，得到 100。字典不按位置，键就是「名牌」。',
        },
        {
          kind: 'fill',
          prompt: '补全函数，让它能把计算结果送出来（填关键字）：',
          code: 'def double(x):\n    ___ x * 2\n\nresult = double(5)',
          answers: ['return'],
          placeholder: '返回关键字',
          hint: '六个字母，意为「返回」。',
          explain: 'return 把 x*2 的结果送出函数；没有 return，函数返回 None，result 就拿不到 10。return 是函数交出答案的出口。',
        },
        {
          kind: 'choice',
          prompt: '你要记录一个怪物的「名字、血量、攻击力」三项属性，哪种数据结构最合适？',
          options: ['字典 {"名字": ..., "血量": ..., "攻击力": ...}', '三个独立变量 name1、hp1、atk1', '列表 ["哥布林", 50, 30]', '三个字符串拼成一句话'],
          answerIndex: 0,
          hint: '想想哪种结构能给每项属性贴上「名牌」，一眼看出谁是谁。',
          explain: '字典能给每项属性起「键名」（名字、血量、攻击力），取值时按名字取，清晰可读。列表靠位置取值（[0]、[1]、[2]），读代码时还得记「第 1 个是名字还是血量」；三个独立变量无法作为一个整体传递。',
        },
        {
          kind: 'order',
          prompt: '把这三行排成「先查键再取值」的安全流程：',
          lines: ['hero = {"金币": 50}', 'if "金币" in hero:', '    print(hero["金币"])'],
          hint: '得先有字典，再用 in 查键，最后才安全取值。',
          explain: '先建字典，再用 in 检查键在不在，确认存在才用方括号取值——这是避免 KeyError 的标准三步法。直接取不存在的键会当场报错。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['def greet(name):', 'return "你好，" + name', 'greet("勇者")'],
          answerLine: 1,
          hint: 'def 那行后面，函数体该缩进没缩进。',
          explain: 'def 行末尾有冒号，下一行必须是缩进的函数体；第 2 行 return 没缩进，Python 会抛 IndentationError。函数体必须缩进，这是 Python 用缩进表示从属的规矩。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['hero = {"名字": "勇者", "血量": 100}', 'print(hero["攻击力"])', 'print("done")'],
          answerLine: 1,
          hint: '字典的方括号里写的键,字典里有吗？',
          explain: 'hero 里只有「名字」「血量」两个键,没有「攻击力」。取不存在的键会抛 KeyError,所以第 2 行报错。访问字典前先用 in 检查("攻击力" in hero)是稳妥做法——也可用 hero.get("攻击力", 默认值) 兜住。',
        },
      ],
    },
  ],
}
