import type { RegionDef } from '../course'

/**
 * 区域 5：字典城（全课程毕业区域，高效入门版）
 *
 * 每关 4-5 题 = 1 选择 + 1 输出 + 1 填空 + 1 改错 (+ 可选 应用)，
 * 螺旋复习 region1-4 全部内容，并最终引入函数与异常处理作为收官。
 */
export const region5: RegionDef = {
  id: '5',
  name: '字典城',
  tagline: '有名字的宝箱城',
  levels: [
    // ============ 5-1 字典基础 ============
    {
      id: '5-1',
      name: '有名字的宝箱',
      xp: 50,
      gold: 18,
      learn: {
        title: '字典：有名字的宝箱城',
        body: [
          '字典（dict）就像一排带名牌的宝箱：每个宝箱有「键」（名牌）和「值」（里面的东西）。写法是 {键: 值}。',
          '取值不按位置，而是按名牌：hero["名字"] 拿到键「名字」对应的值，跟它排第几个无关。',
          '键必须唯一：同一个键后写的值会覆盖先写的。从空字典 {} 起步，用赋值 chest["宝石"] = 3 就能往里添加新的键值对。',
        ],
        code: 'hero = {"名字": "勇者", "血量": 100}\nhero["名字"]          # → "勇者"（按键取值，不看位置）\nhero["血量"] = 80     # 已有的键 = 改值\nhero["金币"] = 50     # 没有的键 = 新增一对\n# 同名键后写覆盖先写：\n{"a": 1, "a": 2}      # → {"a": 2}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '字典和列表最大的区别是？',
          options: ['字典按位置取值，列表按键取值', '字典按键取值，列表按位置取值', '两者都按位置取值', '两者都按键取值'],
          answerIndex: 1,
          hint: '列表用序号 0/1/2，字典用「名牌」键。',
          explain: '列表靠位置（索引 0、1、2…）取值；字典靠键（名牌）取值，跟存放顺序无关。这是两种结构最根本的区别。',
        },
        {
          kind: 'fill',
          prompt: '补全代码，往空字典里添加一对键值（填一个符号）：',
          code: 'chest = {}\nchest["宝石"] ___ 3   # 现在 chest 是 {"宝石": 3}',
          answers: ['='],
          placeholder: '赋值符号',
          hint: '给字典添加新键值对，用的符号和给变量赋值一样。',
          explain: '对不存在的键做赋值 chest["宝石"] = 3，就是新增一对键值；对已存在的键赋值则是修改。这个等号 = 和变量赋值是同一个符号。',
        },
        {
          kind: 'bug',
          prompt: '下面两行里，哪一行会报错？',
          code: ['hero = {"名字": "勇者"}', 'print(hero["金币"])'],
          answerLine: 1,
          hint: '字典里有「金币」这个键吗？',
          explain: 'hero 里只有「名字」这个键，没有「金币」。访问不存在的键会抛 KeyError，程序会中断。访问前先用 in 检查("金币" in hero)是稳妥做法——也可以用 hero.get("金币", 默认值) 兜住。',
        },
        {
          kind: 'output',
          prompt: '执行后 d 是多少？',
          code: 'd = {"a": 1, "a": 2}\nd',
          options: ['{"a": 1, "a": 2}', '{"a": 2}', '{"a": 1}', '报错'],
          answerIndex: 1,
          hint: '同一个键不能出现两次。',
          explain: '字典的键必须唯一，后写的值会覆盖先写的，所以只剩 {"a": 2}。这跟列表不同——列表允许重复元素。',
        },
        {
          kind: 'order',
          prompt: '把这三行排成能顺利执行的顺序：',
          lines: ['chest = {}', 'chest["金币"] = 10', 'chest["金币"]'],
          hint: '得先有字典，才能往里放东西、再取出来。',
          explain: '先建空字典，再给一个新键赋值（新增），最后才能取这个键的值。颠倒顺序的话，后面两行根本找不到对象。',
        },
      ],
    },

    // ============ 5-2 get / in / del ============
    {
      id: '5-2',
      name: '城门守卫',
      xp: 52,
      gold: 18,
      learn: {
        title: '字典守卫术：get / in / del',
        body: [
          '直接用 hero["金币"] 取值时，如果键不存在，Python 会当场翻脸——抛出 KeyError。守卫不让没名牌的人进城。',
          '安全的办法是 hero.get("金币", 0)：键存在就返回对应值，不存在就返回你给的默认值 0，绝不报错。',
          '用 "金币" in hero 可以先查键在不在（返回 True/False）；del hero["金币"] 能删掉一对键值；赋值 hero["金币"] = x 对已有键是改、对新键是增。',
        ],
        code: 'hero = {"名字": "勇者"}\nhero["名字"]          # → "勇者"\nhero["金币"]          # → KeyError！没有这个键\nhero.get("金币", 0)   # → 0（键不存在，用默认值）\n"金币" in hero        # → False\nhero["金币"] = 50     # 没有=新增\ndel hero["金币"]      # 删除这对键值',
      },
      questions: [
        {
          kind: 'fill',
          prompt: '补全代码，安全地取「金币」（找不到时返回 0，填一个关键字或方法名）：',
          code: 'hero = {"名字": "勇者"}\ngold = hero.___("金币", 0)',
          answers: ['get'],
          placeholder: '三个字母',
          hint: '是字典的安全取值方法，找不到时不报错。',
          explain: 'get("金币", 0) 找不到键「金币」时返回默认值 0，绝不报错。这是字典安全取值的标准写法。',
        },
        {
          kind: 'output',
          prompt: '执行后 result 是多少？',
          code: 'hero = {"血量": 100}\nresult = "血量" in hero',
          options: ['True', 'False', '100', '报错'],
          answerIndex: 0,
          hint: 'in 查的是「键在不在」，不是值。',
          explain: '"血量" in hero 检查键「血量」是否存在，返回 True。in 查的是键，不是值，也不是位置。',
        },
        {
          kind: 'bug',
          prompt: '下面两行里，哪一行会报错？',
          code: ['hero = {"名字": "勇者"}', 'del hero["金币"]'],
          answerLine: 1,
          hint: 'del 要删的键存在吗？',
          explain: '第 2 行：del 删除不存在的键会抛 KeyError。删除前先用 "金币" in hero 确认存在，或者用 try/except 兜住。',
        },
        {
          kind: 'output',
          prompt: '执行后 chest 的内容是？',
          code: 'chest = {"宝石": 1}\nchest["宝石"] = 5\nchest["金币"] = 10',
          options: ['{"宝石": 5, "金币": 10}', '{"宝石": 1, "金币": 10}', '{"宝石": 5}', '报错'],
          answerIndex: 0,
          hint: '已有的键赋值=改；没有的键赋值=增。',
          explain: 'chest["宝石"]=5 改了已有键（1→5）；chest["金币"]=10 新增了一对。所以最终是 {"宝石": 5, "金币": 10}。一个等号同时承担「改」和「增」两种角色，取决于键在不在。',
        },
        {
          kind: 'fill',
          prompt: '补全代码，删掉字典里的一对键值（填一个关键字）：',
          code: '___ hero["血量"]   # 删掉这对键值',
          answers: ['del'],
          placeholder: '删除关键字',
          hint: '三个字母，意为 delete（删除）。',
          explain: 'del hero["血量"] 删除键「血量」及其值。删完之后再取这个键就会 KeyError。del 也能删变量，是个通用删除关键字。',
        },
      ],
    },

    // ============ 5-3 函数 def / return ============
    {
      id: '5-3',
      name: '咒语工坊',
      xp: 55,
      gold: 20,
      learn: {
        title: '函数：把咒语封进卷轴',
        body: [
          '函数（function）就像封进卷轴的咒语：定义一次，之后随时念出来用。用 def 定义，括号里写参数（咒语需要的材料），冒号后缩进的几行是咒语正文。',
          'return 把结果送出函数；如果不写 return，函数会默默返回 None。函数「先定义、后调用」——调用时写函数名加括号。',
          '参数是函数内部的临时变量：调用时把值传进去，函数用完就丢，不影响外面的同名变量。',
        ],
        code: 'def greet(name):\n    return "你好，" + name\n\ngreet("勇者")      # → "你好，勇者"\n\ndef show_hp():\n    print("血量：100")   # 没有 return\n\nresult = show_hp()   # → 打印「血量：100」，result 是 None',
      },
      questions: [
        {
          kind: 'fill',
          prompt: '补全代码，定义一个函数（填关键字）：',
          code: '___ greet(name):\n    return "你好，" + name',
          answers: ['def'],
          placeholder: '定义函数的关键字',
          hint: '三个字母，是 define（定义）的缩写。',
          explain: 'def 是定义函数的关键字，后面跟函数名和参数列表，冒号结尾，下一行缩进写函数体。漏了 def 就不是函数定义。',
        },
        {
          kind: 'output',
          prompt: '执行后 result 是什么？',
          code: 'def show_hp():\n    print("血量：100")\n\nresult = show_hp()',
          options: ['"血量：100"', '100', 'None', '报错'],
          answerIndex: 2,
          hint: '函数没有写 return 会怎样？',
          explain: 'show_hp 只 print 不 return，所以返回值是 None。print 把字打到屏幕上，但函数本身「没给出答案」——result 拿到的是 None。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['def greet(name):', 'return "你好，" + name', 'greet("勇者")'],
          answerLine: 1,
          hint: 'def 那行后面，函数体该缩进没缩进。',
          explain: 'def 行末尾有冒号，下一行必须是缩进的函数体；第 2 行 return 没缩进，Python 会抛 IndentationError。函数体必须缩进，这是 Python 用缩进表示从属的规矩。',
        },
        {
          kind: 'output',
          prompt: '执行后 add(3, 5) 的返回值是？',
          code: 'def add(a, b):\n    return a + b\n\nadd(3, 5)',
          options: ['8', '35', 'None', '报错'],
          answerIndex: 0,
          hint: '参数按位置对应：a 接 3，b 接 5。',
          explain: '调用 add(3, 5) 时，a=3、b=5（按位置对应），return 3+5=8。多个参数按顺序一一对应。',
        },
        {
          kind: 'order',
          prompt: '把这三行排成能顺利执行的顺序：',
          lines: ['def greet(name):', '    return "你好，" + name', 'greet("勇者")'],
          hint: 'def 那行在前，缩进的函数体紧跟其后，最后才是调用。',
          explain: '先写 def 头、再写缩进的函数体（两者一起构成定义），最后才能调用。调用放在定义之前会 NameError。',
        },
      ],
    },

    // ============ 5-4 异常处理 try / except ============
    {
      id: '5-4',
      name: '错误避风港',
      xp: 55,
      gold: 20,
      learn: {
        title: '异常处理：try / except',
        body: [
          '出错时 Python 抛异常（Exception），程序当场中断。try/except 可以「兜住」异常，让程序继续跑——写健壮代码的标配。',
          'try 块放可能出错的代码；except 错误类型 后跟处理代码——错误类型不匹配则不兜，异常照常上抛。',
          'finally 块不管有没有出错都会执行——常用来收尾（关文件、释放资源）。',
        ],
        code: 'try:\n    x = 1 / 0             # 会抛 ZeroDivisionError\nexcept ZeroDivisionError:\n    print("抓住除零")     # 类型匹配才兜住\nexcept ValueError:\n    pass                    # int("abc") 是 ValueError,不兜 0 除\nexcept:\n    print("兜底")         # 不写类型,什么都接',
      },
      questions: [
        {
          kind: 'fill',
          prompt: '补全代码，填异常处理的关键字：',
          code: 'try:\n    print(int("abc"))\n___ ValueError:\n    print("v")',
          answers: ['except'],
          placeholder: '兜异常的关键字',
          hint: '六个字母，是「除……之外」的意思。',
          explain: 'except 关键字后跟异常类型，定义「这种错误出现时该怎么办」。int("abc") 抛 ValueError，被 except ValueError 抓住。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['try:', '    x = 1 / 0', 'except ValueError:', '    print("v")', 'print("done")'],
          answerLine: 1,
          hint: 'except 后面写的错误类型对得上吗？',
          explain: '1/0 抛的是 ZeroDivisionError，但 except 写的是 ValueError——类型不匹配，except 不兜，异常照常上抛。第 2 行 x = 1/0 是出错源头。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("caught")\nprint("end")',
          options: ['caught 和 end', 'end', '报错 ZeroDivisionError', 'caught'],
          answerIndex: 0,
          hint: '1/0 会抛什么异常？except 抓住了之后呢？',
          explain: '1/0 抛 ZeroDivisionError，被 except 抓住，打印 "caught"。try 块「安全结束」后继续往下跑，再打印 "end"。',
        },
        {
          kind: 'choice',
          prompt: 'try/except 的主要作用是？',
          options: [
            '加速代码执行',
            '把可能出错的代码「兜」起来，出错时不中断程序',
            '代替 if/else 做判断',
            '让 print 输出更快',
          ],
          answerIndex: 1,
          hint: '想想 except 这个词的意思。',
          explain: 'try/except 的作用是「兜住」异常：try 块出错时，except 块接管处理，程序不会当场中断。可以指定异常类型，只兜匹配的错误。',
        },
        {
          kind: 'output',
          prompt: '这段代码运行后输出什么？',
          code: 'try:\n    print("OK")\nexcept:\n    print("NO")',
          options: ['OK', 'NO', 'OK 和 NO 都打印', '报错'],
          answerIndex: 0,
          hint: 'try 块没出错，except 会执行吗？',
          explain: 'try 块顺利跑完没出错，except 块就不执行——只打印 "OK"。except 是出错时的「备用方案」，平时不跑。',
        },
      ],
    },

    // ============ 5-4 进阶挑战：老坑新游（原秘境岛内容迁入） ============
    {
      id: '5-4',
      name: '老坑新游（进阶挑战）',
      xp: 55,
      gold: 22,
      learn: {
        title: '老坑新游：把学过的坑再踩一遍（这次是故意的）',
        body: [
          '进阶挑战：8 道题全部出自前 5 个区域的内容，但每一道都是真实项目里高频翻车的角落——"运行结果和直觉不一样"恰恰是考点本身。',
          '新面孔速览：is 比较身份（是不是同一个对象），== 比较值；b = a 不复制列表，两个名字共享同一份，想复制用 a.copy()。',
          '另外三个：元组 (1, 2) 是列表的不可变亲戚，t[0] = 9 会报错；默认参数 bag=[] 只在 def 时创建一次，所有调用共享（可变默认参数是著名大坑）；s[::-1] 是步长 -1 的切片，整串倒着走。',
          '心法：不要猜"Python 会帮我修正"，要问"规范就是这么写的"。每道题的正确答案都可以用 python 实测复现。',
        ],
        code: '# 这几道题的考点在课程主线之外半步：\n# 元组、is 与 ==、可变默认参数、负步长切片。\n# 先读学习卡，再逐题击破。',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'a = [1, 2]、b = [1, 2]、c = a。下面哪些判断的结果是 True？',
          options: ['a == b 且 a is c', 'a is b 且 a == c', 'a == b 且 a is b', 'a is b 且 a is c'],
          answerIndex: 0,
          hint: '== 比较值，is 比较身份（是不是同一个对象）。',
          explain: 'a == b：值相等 → True。c = a 让 c 和 a 指向同一个列表 → a is c 是 True。但 a 和 b 是两个独立创建的列表，就算内容一样，a is b 也是 False。这就是 is 和 == 的根本区别：一个比身份，一个比值。',
        },
        {
          kind: 'output',
          prompt: '执行后输出什么？',
          code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(len(a))',
          options: ['3', '4', '报错', '看情况'],
          answerIndex: 1,
          hint: 'b = a 复制了列表吗？',
          explain: 'b = a 不复制列表，只是让两个名字指向同一个列表。b.append(4) 改的就是 a 也能看到的那个列表，所以 len(a) 是 4。想真正复制要用 a.copy() 或 list(a)。这是 Python 高频坑第一名。',
        },
        {
          kind: 'output',
          prompt: '执行后输出的两行分别是？',
          code: 'def collect(x, bag=[]):\n    bag.append(x)\n    return bag\n\nprint(collect(1))\nprint(collect(2))',
          options: ['[1] 和 [2]', '[1] 和 [1, 2]', '[1] 和 [1]', '报错'],
          answerIndex: 1,
          hint: '默认参数 bag=[] 在什么时候创建？',
          explain: '默认参数 bag=[] 只在 def 语句执行时创建一次，之后所有调用共享同一个列表。第一次调用得 [1]，第二次往同一个列表里追加 2，得 [1, 2]。可变对象做默认参数是著名的坑——正确写法是 bag=None 然后在函数体里 bag = []。',
        },
        {
          kind: 'output',
          prompt: '执行后输出什么？',
          code: 's = "isle"\ns.upper()\nprint(s)',
          options: ['ISLE', 'isle', 'Isle', '报错'],
          answerIndex: 1,
          hint: '字符串方法会修改原字符串吗？',
          explain: '字符串不可变：s.upper() 返回一个全新的大写字符串，原字符串 s 一个字符都不会变——而这里没有把返回值接住，直接丢掉了。想拿到大写结果要写 s = s.upper()。列表的 .append() 是原地修改，字符串方法全是返回新值，两类行为要分清。',
        },
        {
          kind: 'fill',
          prompt: '补全方法名，安全地取「宝石」：键不存在时返回 0 而不是报错：',
          code: 'chest = {"金币": 10}\ngem = chest.___("宝石", 0)\nprint(gem)   # → 0',
          answers: ['get'],
          placeholder: '三个字母',
          hint: '字典的安全取值方法，第二个参数是缺省值。',
          explain: 'chest.get("宝石", 0)：键存在返回对应值，不存在返回第二个参数 0，绝不抛 KeyError。chest["宝石"] 这种方括号写法在键不存在时会当场报错。秘境岛之外，这是写配置读取的标准姿势。',
        },
        {
          kind: 'bug',
          prompt: '下面哪一行会报错？',
          code: ['t = (1, 2, 3)', 't[0] = 9', 'print(t)'],
          answerLine: 1,
          hint: '圆括号装的这一家子，有个雷打不动的规矩。',
          explain: '第 2 行：元组不可变，t[0] = 9 抛 TypeError: \'tuple\' object does not support item assignment。元组适合装"定死不变"的一组值（坐标、日期的年月日）；需要修改就用列表。这是两种容器最核心的分界线。',
        },
        {
          kind: 'output',
          prompt: '执行后输出什么？',
          code: 's = "abcde"\nprint(s[::-1])',
          options: ['abcde', 'edcba', 'a', '报错'],
          answerIndex: 1,
          hint: '步长为 -1 的切片会怎么走？',
          explain: 's[::-1] 表示"整串、步长 -1"：从尾到头倒着切，得到反转字符串 "edcba"。切片三段式 [start:stop:step] 里 start/stop 省略就是"取到头"，负步长把方向反过来。这是 Python 反转字符串/列表最简洁的惯用写法。',
        },
        {
          kind: 'output',
          prompt: '执行后输出什么？（中文同样能切）',
          code: 'name = "代码群岛"\nprint(name[1:3])',
          options: ['码群', '代码', '群岛', '报错'],
          answerIndex: 0,
          hint: '含头不含尾，从索引 1 切到索引 3 之前。',
          explain: '中文字符串一样按索引切片：name[1:3] 从索引 1（码）取到索引 3 之前（不含群），得 "码群"。含头不含尾的规则对任何字符串都成立，中文、emoji 也不例外——切片按字符数，不是按字节。',
        },
      ],
    },

    // ============ 5-B Boss: 全课程毕业测验 ============
    {
      id: '5-B',
      name: '字典城大测验',
      xp: 140,
      gold: 60,
      boss: true,
      learn: {
        title: 'Boss：全课程毕业测验',
        body: [
          '这是「代码群岛」的最终关卡！6 道题覆盖变量、字符串、分支、循环、列表、字典、函数——整段旅程的精华浓缩于此。',
          '答错会当场给解析，别怕试错。全对零提示才能拿到 ★★★ 和完整战利品。整理行囊，出发吧！',
        ],
      },
      questions: [
        {
          kind: 'output',
          prompt: '执行后 total 是多少？',
          code: 'total = 0\nfor i in range(1, 4):\n    total = total + i\ntotal',
          options: ['6', '10', '3', '7'],
          answerIndex: 0,
          hint: 'range(1, 4) 生成哪些数？全部加起来。',
          explain: 'range(1, 4) 生成 1、2、3（含头不含尾），循环累加：0+1+2+3=6。这是"累加器"模式——循环里最常用的写法。',
        },
        {
          kind: 'fill',
          prompt: '补全函数，让它能把计算结果送出来（填关键字）：',
          code: 'def double(x):\n    ___ x * 2\n\nresult = double(5)',
          answers: ['return'],
          placeholder: '返回关键字',
          hint: '六个字母，意为「返回」。',
          explain: 'return 把 x*2 的结果送出函数；没有 return，函数返回 None，result 就拿不到 10。return 是函数交出答案的出口。',
        },
        {
          kind: 'bug',
          prompt: '下面这段代码哪一行会报错？',
          code: ['hero = {"名字": "勇者", "血量": 100}', 'print(hero["攻击力"])'],
          answerLine: 1,
          hint: '字典的方括号里写的键，字典里有吗？',
          explain: 'hero 里只有「名字」「血量」两个键，没有「攻击力」。取不存在的键会抛 KeyError，所以第 2 行报错。访问字典前先用 in 检查("攻击力" in hero)是稳妥做法——也可用 hero.get("攻击力", 默认值) 兜住。',
        },
        {
          kind: 'output',
          prompt: '执行后 msg 是什么？',
          code: 'gold = 50\nif gold >= 100:\n    msg = "富有"\nelse:\n    msg = "贫穷"',
          options: ['"富有"', '"贫穷"', 'None', '报错'],
          answerIndex: 1,
          hint: 'gold 够不够 100？',
          explain: 'gold=50 不满足 >=100，走 else 分支，msg="贫穷"。if/else 二选一，条件为假就执行 else。',
        },
        {
          kind: 'choice',
          prompt: '你要记录一个怪物的「名字、血量、攻击力」三项属性，哪种数据结构最合适？',
          options: ['字典 {"名字": ..., "血量": ..., "攻击力": ...}', '三个独立变量 name1、hp1、atk1', '列表 ["哥布林", 50, 30]', '三个字符串拼成一句话'],
          answerIndex: 0,
          hint: '想想哪种结构能给每项属性贴上「名牌」，一眼看出谁是谁。',
          explain: '字典能给每项属性起「键名」（名字、血量、攻击力），取值时按名字取，清晰可读。列表靠位置取值（[0]、[1]、[2]），读代码时还得记「第 1 个是名字还是血量」；三个独立变量无法作为一个整体传递。',
        },
        {
          kind: 'output',
          prompt: '执行后 result 是多少？',
          code: 'def f(x, y=10):\n    return x + y\n\nf(3)',
          options: ['3', '13', '10', '报错'],
          answerIndex: 1,
          hint: '没传的参数会用什么？',
          explain: 'y 没传，自动用默认值 10，所以 f(3) = 3 + 10 = 13。默认参数让函数调用更灵活——常用值可以不传。毕业快乐！',
        },
      ],
    },
  ],
}