import type { RegionDef } from '../course'

/**
 * 区域 1：流式新港（C++ 基础入门）
 *
 * 每关 6 题 = 2 选择 + 2 输出 + 1 填空 + 1 改错（或排序），Boss 关 9 题全线综合。
 * 所有题目代码已在 g++ 8.1.0（-std=c++14）下真机验算。区域 id 用 cpp 前缀，
 * 与 Python（'1'..'5'）、JS（'j1'..'j4'）课程在错题本中互不冲突。
 */
export const regionCpp1: RegionDef = {
  id: 'cpp1',
  name: '流式新港',
  tagline: '从 C 的旧地图驶入 C++ 的新航道',
  levels: [
    // ============ cpp1-1 iostream 与 cout ============
    {
      id: 'cpp1-1',
      name: '第一面风帆',
      xp: 44,
      gold: 15,
      learn: {
        title: 'cout：把战报送上海面',
        body: [
          '#include <iostream> 是 C++ 的第一句咒语：把「输入输出库」请上船，才有 cout、cin、endl 可用。它以 # 开头，结尾不加分号。',
          'std::cout 是「通往屏幕的传送带」。<< 像装货爪，把内容一件件放上传送带：std::cout << "满帆";。可以连续装货：std::cout << "满" << "帆";。',
          'std::endl 输出换行并刷新缓冲区（立刻送达屏幕）；"\\n" 只换行、不刷新。日常两者通用，问「区别」时记住：endl 多做一步刷新。',
          'std:: 前缀有点长。在文件顶部写 using namespace std;，之后就能直接写 cout、endl——省事；大工程里建议保留 std::，避免撞名。',
        ],
        code: '#include <iostream>          // 引入输入输出库\nint main() {\n    std::cout << "流式新港" << std::endl;   // endl 换行\n    std::cout << "满帆!\\n";                  // "\\n" 也能换行\n    return 0;\n}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: '要让 cout 上船干活，文件开头必须写下哪一句？',
          options: ['#include <iostream>', '#include <string>', 'using namespace std;', 'import iostream'],
          answerIndex: 0,
          hint: '「库」要先请上船，cout 才有得用。',
          explain: '#include <iostream> 把输入输出库包含进来，cout、cin、endl 都住在这里。import 是 Python 的写法，C++ 不认识；using namespace std 只是省前缀，不能代替 include。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nint main() {\n    std::cout << "满帆" << std::endl;\n    std::cout << "顺风";\n    return 0;\n}',
          options: ['两行：满帆 / 顺风', '同一行：满帆顺风', '报错', '什么都不输出'],
          answerIndex: 0,
          hint: '第一个 cout 有 endl，第二个没有。',
          explain: '第一个 cout 用 endl 收尾，「满帆」后面换行；第二个 cout 没有 endl，光标停在「顺风」后面。屏幕上共两行：满帆 / 顺风。已用编译器实测输出一致。',
        },
        {
          kind: 'choice',
          prompt: 'std::endl 和 "\\n" 都能换行，endl 还多做了一件什么事？',
          options: ['刷新输出缓冲区，立刻送到屏幕', '结束整个程序', '把屏幕清空', '什么都不多做'],
          answerIndex: 0,
          hint: '除了送达，endl 还会「催单」。',
          explain: 'endl = 换行 + 刷新缓冲区。输出的字先在缓冲区排队，endl 会喊一声「立刻发货」；"\\n" 只默默换行、不催单。',
        },
        {
          kind: 'fill',
          prompt: '补全这行输出语句，让战报出海：',
          code: '#include <iostream>\nusing namespace std;\n\n___ << "满帆!" << endl;',
          answers: ['cout'],
          placeholder: '通往屏幕的流对象',
          hint: 'using namespace std 之后，std:: 可以省掉，直接喊名字。',
          explain: '写了 using namespace std; 后，std::cout 可以直接写成 cout。填好后运行会输出「满帆!」。注意此空精确匹配 cout。',
        },
        {
          kind: 'bug',
          prompt: '这段程序编译报错，问题出在哪一行？',
          code: ['#include <iostream>', 'int main() {', '    std::cout << "满帆" << std::endl', '    return 0;', '}'],
          answerLine: 2,
          hint: 'C++ 的每条语句结尾都要挂一个小钩子。',
          explain: '第 3 行结尾少了分号。C++ 每条语句必须以 ; 结束，编译器会在这行末尾报 expected \';\'。找错时先盯最长的语句看结尾——分号是新手丢分重灾区。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "起航" << endl;\n    return 0;\n}',
          options: ['起航', 'std::起航', '报错：不认识 cout', '什么都不输出'],
          answerIndex: 0,
          hint: 'using namespace std 把 std:: 的行李都卸下来了。',
          explain: '文件顶部写了 using namespace std;，于是 cout、endl 不用再加 std:: 前缀，直接可用，输出「起航」。若没写这行，这里会报「cout 未声明」。',
        },
        {
          kind: 'output',
          prompt: '这行代码输出什么？',
          code: 'cout << "HP:" << 100 << endl;',
          options: ['HP:100', 'HP: 100', 'HP:%d', '报错'],
          answerIndex: 0,
          hint: '<< 可以连续装货，文字数字混着装。',
          explain: '<< 链式把每件货依次送上传送带："HP:" 原样输出，100 按数字输出，endl 换行。cout 不用挑格式符——数字文字混装它都认识，比 printf 省心。',
        },
        {
          kind: 'choice',
          prompt: 'cout << 1 << 2 << endl; 输出什么？',
          options: ['1 2', '12', '3', '1 和 2 分两行'],
          answerIndex: 1,
          hint: 'cout 不会自作主张加空格。',
          explain: '两个 << 依次输出 1 和 2，中间什么都没有，屏幕上是 12。想要空格得自己装：cout << 1 << " " << 2 << endl;',
        },
        {
          kind: 'fill',
          prompt: '补全运算符，把文字送上传送带：',
          code: 'cout ___ "帆" << endl;   // 输出：帆',
          answers: ['<<'],
          placeholder: '两个小于号',
          hint: '箭头指向屏幕——数据流的方向。',
          explain: 'cout 用 << 把右边的东西送向屏幕（箭头指向外）。cin 正好相反用 >>（箭头指向变量）。方向写反直接编译报错。',
        },
      ],
    },

    // ============ cpp1-2 cin 与 string ============
    {
      id: 'cpp1-2',
      name: '接舷与缆绳',
      xp: 45,
      gold: 16,
      learn: {
        title: 'cin 与 string：靠港接收货物',
        body: [
          'cin 是「从键盘来的传送带」，方向和 cout 相反：cin >> gold; 把你敲的内容卸进变量。>> 的箭头指向变量，指哪儿卸哪儿。',
          'std::string 是 C++ 的字符串类型，要用 #include <string>。定义：string name = "浪花";。用 + 拼接：string full = a + b;。用 == 比较：比的是内容是否一字不差。',
          'cin >> s 读一个词：遇到空格或回车就停。想读一整行要用别的工具（以后再教），今天先把单词接稳。',
        ],
        code: '#include <iostream>\n#include <string>            // 用 string 要引入字符串库\nusing namespace std;          // 之后 cout/cin/string 不用再加 std::\n\nint main() {\n    string ship = "黑";\n    ship = ship + "珍珠";     // + 拼接\n    cout << ship << endl;     // → 黑珍珠\n\n    string guess;\n    cin >> guess;             // 读入一个词（空格/回车截止）\n    if (guess == ship) {      // == 比较内容\n        cout << "猜对了!" << endl;\n    }\n    return 0;\n}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'cin 和 cout 的箭头方向，哪个是对的？',
          options: ['cin >> gold;（箭头指向变量）', 'cin << gold;（箭头指向 cin）', 'cin ** gold;', '方向随便写，都能编译'],
          answerIndex: 0,
          hint: '货物从键盘卸进变量，箭头指向谁？',
          explain: '>> 表示「从 cin 取出、送进右边变量」，所以箭头指向 gold。写反成 cin << gold 会直接编译报错，这是新手常见错。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string a = "木";\n    string b = "筏";\n    string boat = a + b;\n    cout << boat << endl;\n    return 0;\n}',
          options: ['木筏', '木 筏', '报错', '什么都不输出'],
          answerIndex: 0,
          hint: '+ 对 string 来说不是算术，是拼接。',
          explain: 'string 的 + 表示拼接：a + b 把两段字连成一串「木筏」。注意没有空格——+ 不会自动帮你加空格，想要空格得自己写 a + " " + b。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string have = "金币";\n    string want = "金币";\n    if (have == want) {\n        cout << "相同" << endl;\n    } else {\n        cout << "不同" << endl;\n    }\n    return 0;\n}',
          options: ['相同', '不同', '金币', '报错'],
          answerIndex: 0,
          hint: '== 对 string 比较的是内容。',
          explain: 'string 用 == 比较内容：have 和 want 都是「金币」，一字不差，条件成立，输出「相同」。',
        },
        {
          kind: 'fill',
          prompt: '补全拼接符号，把两段船名连起来：',
          code: 'string first = "黑";\nstring last = "珍珠";\nstring ship = first ___ last;   // → 黑珍珠',
          answers: ['+'],
          placeholder: '一个符号',
          hint: 'string 的「连体术」，用的就是算术里的加号。',
          explain: 'string + string 会拼接出新字符串：first + last 得到「黑珍珠」。已实测编译运行无误。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行排成一段完整程序（输出「锚」）：',
          lines: ['#include <iostream>', 'using namespace std;', 'int main() {', '    cout << "锚" << endl;', '    return 0;', '}'],
          hint: '先 include，再 using，然后 main 开工，收工 return 0，最后合上大括号。',
          explain: '完整程序骨架：#include 引库 → using 声明 → main 函数开工 → 干活 → return 0 收工 → } 合上。main 里的语句从上到下依次执行。',
        },
        {
          kind: 'bug',
          prompt: '这段程序编译报错，问题出在哪一行？',
          code: ['#include <iostream>', 'using namespace std;', 'int main() {', '    int gold;', '    cin << gold;', '    cout << gold << endl;', '    return 0;', '}'],
          answerLine: 4,
          hint: '读入的箭头方向写反了。',
          explain: '第 5 行把 >> 写成了 <<。cin 是「读入」，要用 >> 把数据送进变量；写成 cin << gold，编译器找不到匹配的 <<，报 no match for operator<<。记口诀：cout 往外怼（<<），cin 往里卸（>>）。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出什么？',
          code: 'string a = "abc";\nstring b = a + "de";\ncout << b.size();',
          options: ['5', '3', '2', '报错'],
          answerIndex: 0,
          hint: '先拼接，再数长度。',
          explain: 'a + "de" 得 "abcde"，size() 数出 5 个字符。string 的拼接和计数可以随接随用——每个方法都返回能直接接着用的对象。',
        },
        {
          kind: 'choice',
          prompt: 'cin >> name; 用户输入 hello world（中间有空格），name 里接到什么？',
          options: ['"hello world" 整句', '"hello"（空格前的那段）', '"world"（空格后的那段）', '报错'],
          answerIndex: 1,
          hint: '>> 读一个"词"，遇到空格就停。',
          explain: 'cin >> 遇到空格就截止，name 只接到 "hello"，"world" 留在输入队列里等下一次读取。想读一整行要用 getline(cin, name)——后面的章节再教。',
        },
        {
          kind: 'fill',
          prompt: '补全符号，把两段船名拼在一起：',
          code: 'string a = "黑";\nstring b = "珍珠";\ncout << a ___ b << endl;   // → 黑珍珠',
          answers: ['+'],
          placeholder: '一个符号',
          hint: 'string 的拼接和算术共用一个符号。',
          explain: 'string + string 首尾相接得 "黑珍珠"。C++ 让 string 也能用 + 号（运算符重载）——比 C 的字符串函数优雅得多。',
        },
      ],
    },

    // ============ cpp1-3 引用 ============
    {
      id: 'cpp1-3',
      name: '镜像舱',
      xp: 44,
      gold: 15,
      learn: {
        title: '引用：给变量起别名',
        body: [
          'int& r = x; 定义了一个「引用」：r 不是新变量，是 x 的别名——同一个舱室挂了两块名牌。改 r 就是改 x，改 x 也等于改 r。',
          '引用有条铁律：出生时必须绑定，且终身不改嫁。int& r;（不初始化）直接编译报错；绑定后不能再指向别的变量。指针正好相反：可以空、可以改指向，是个自由散漫的家伙。',
          '引用最实用的场景是函数参数：void refill(int& hp)。传进去的是本尊的别名，函数里改 hp，外面的变量真的被改了。不加 & 的话，函数拿到的是复印件，怎么改都碰不到原件。',
        ],
        code: '#include <iostream>\nusing namespace std;\n\nvoid refill(int& hp) {      // int& ：hp 是外面变量的别名\n    hp = 100;\n}\n\nint main() {\n    int hp = 30;\n    int& alias = hp;        // 引用必须初始化：出生即绑定\n    alias = 80;\n    cout << hp << endl;     // → 80（改 alias 就是改 hp）\n\n    refill(hp);\n    cout << hp << endl;     // → 100\n    return 0;\n}',
      },
      questions: [
        {
          kind: 'choice',
          prompt: 'int& r = x; 里，r 到底是什么？',
          options: ['x 的别名，和 x 是同一块内存', 'x 的一份副本', '指向 x 的指针', '一个全新的变量'],
          answerIndex: 0,
          hint: '引用 = 同一个舱室挂两块名牌。',
          explain: '引用 r 只是 x 的别名，两者是同一块内存，改 r 就是改 x。副本是 int r = x;（不加 &）才会发生的事。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nusing namespace std;\nint main() {\n    int hp = 100;\n    int& alias = hp;\n    alias = 80;\n    cout << hp << endl;\n    return 0;\n}',
          options: ['80', '100', '180', '报错'],
          answerIndex: 0,
          hint: 'alias 不是副本，是 hp 本尊的别名。',
          explain: 'alias 是 hp 的引用，alias = 80 改的就是 hp 本尊，所以输出 80。如果写的是 int alias = hp;（没有 &），alias 只是副本，输出的会是 100。',
        },
        {
          kind: 'bug',
          prompt: '这段程序编译报错，问题出在哪一行？',
          code: ['#include <iostream>', 'using namespace std;', 'int main() {', '    int hp = 100;', '    int& alias;', '    alias = hp;', '    cout << alias << endl;', '    return 0;', '}'],
          answerLine: 4,
          hint: '引用有一条「出生即绑定」的铁律。',
          explain: '第 5 行定义引用却没有初始化，编译器报 declared as reference but not initialized。C++ 规定引用必须在定义时绑定一个变量，正确写法：int& alias = hp;。',
        },
        {
          kind: 'fill',
          prompt: '补全参数里的符号，让函数能直接修改外面的血量：',
          code: 'void boost(int___ hp) {   // 补上符号：hp 是外面变量的别名\n    hp = hp + 10;\n}\n\nint main() {\n    int hp = 90;\n    boost(hp);            // → hp 变成 100\n}',
          answers: ['&'],
          placeholder: '一个符号，引用的标志',
          hint: '「引用」的 & 就住在类型名和变量名之间。',
          explain: 'int& hp 表示参数是外面变量的别名，函数里改 hp 真的能改到外面（实测 boost 后 hp 从 90 变 100）。少了 & 就是普通传值——函数拿到复印件，改完就扔。',
        },
        {
          kind: 'choice',
          prompt: '关于引用和指针的区别，下列说法正确的是？',
          options: ['引用必须初始化，且不能改绑别的变量', '引用可以先不指向任何东西', '指针必须初始化，引用可以随便', '两者完全一样，随便换用'],
          answerIndex: 0,
          hint: '一个守身如玉，一个自由散漫。',
          explain: '引用出生必须绑定、终身不改绑、没有「空引用」；指针可以先为空、之后改指向。所以传参数优先用引用：更安全，写法也更干净。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nusing namespace std;\nvoid refill(int& hp) {\n    hp = 100;\n}\nint main() {\n    int hp = 30;\n    refill(hp);\n    cout << hp << endl;\n    return 0;\n}',
          options: ['100', '30', '130', '报错'],
          answerIndex: 0,
          hint: 'refill 的参数带 &，拿到的是本尊。',
          explain: 'refill(int& hp) 的参数是引用，main 里的 hp 传进去后，函数里 hp = 100 改的就是外面的 hp，输出 100。若参数写成 int hp（无 &），输出的仍是 30。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出什么？',
          code: 'void swap(int& x, int& y) {\n    int t = x;\n    x = y;\n    y = t;\n}\nint main() {\n    int m = 1, n = 2;\n    swap(m, n);\n    cout << m << n;\n    return 0;\n}',
          options: ['12', '21', '11', '报错'],
          answerIndex: 1,
          hint: '引用参数直接改原件。',
          explain: 'swap 的参数是 int& 引用：x、y 就是 m、n 的别名，函数里交换的是原件。调用后 m=2、n=1，输出 21。C 里要靠指针才能做到的事，C++ 用引用写得更干净。',
        },
        {
          kind: 'choice',
          prompt: 'int a = 5; int& r = a; 执行 r = r + 1; 之后 a 是？',
          options: ['5', '6', '1', '报错'],
          answerIndex: 1,
          hint: 'r 不是副本，是 a 的别名。',
          explain: 'r 是 a 的引用，r = r + 1 就是 a = a + 1，a 变成 6。对引用做任何操作都等于对原变量操作——它们是同一块内存的两个名字。',
        },
        {
          kind: 'output',
          prompt: '这段代码输出什么？',
          code: 'void addOne(int& v) {\n    v += 1;\n}\nint main() {\n    int n = 5;\n    addOne(n);\n    addOne(n);\n    cout << n;\n    return 0;\n}',
          options: ['5', '6', '7', '报错'],
          answerIndex: 2,
          hint: '每调用一次，外面的 n 就加一次。',
          explain: 'addOne 的参数是引用，每次调用都把外面的 n 加 1：两次调用后 n = 7。引用参数是让函数"持久改变"外部变量的标准手段。',
        },
      ],
    },

    // ============ cpp1-B Boss：流式新港全线综合 ============
    {
      id: 'cpp1-B',
      name: '流式新港大测验',
      xp: 100,
      gold: 40,
      boss: true,
      learn: {
        title: 'Boss：流式新港全线复习',
        body: [
          '这一关没有新知识。9 道题横扫三关：cout/endl、cin/string、引用别名。答错当场给解析，放心冲。',
          '全对零提示才能拿到 ★★★ 和完整战利品。港口潮水已涨起，扬帆！',
        ],
      },
      questions: [
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "锚" << "\\n";\n    cout << "帆" << endl;\n    cout << "海";\n    return 0;\n}',
          options: ['三行：锚 / 帆 / 海', '两行：锚帆 / 海', '一行：锚帆海', '报错'],
          answerIndex: 0,
          hint: 'endl 和 "\\n" 都换行；没有换行符就续在后面。',
          explain: '"\\n" 和 endl 都让光标跳到下一行，第三个 cout 没有换行符，光标停在「海」后面。共三行：锚 / 帆 / 海（已实测）。',
        },
        {
          kind: 'choice',
          prompt: '关于引用，下列说法正确的是？',
          options: ['引用必须在定义时初始化', '引用定义后可以改绑其他变量', 'int& r; 不初始化也没关系', '引用就是指针的马甲，一模一样'],
          answerIndex: 0,
          hint: '出生即绑定，终身不改嫁。',
          explain: '引用三律：必须初始化、不能改绑、没有「空引用」。指针可以空、可以改指向，两者不是一回事。',
        },
        {
          kind: 'fill',
          prompt: '补全头文件，把输入输出库请上船：',
          code: '#include <___>\n\nint main() {\n    std::cout << "起航" << std::endl;\n    return 0;\n}',
          answers: ['iostream'],
          placeholder: '输入输出库的名字',
          hint: '三个音节：i-o-stream。',
          explain: '#include <iostream> 引入输入输出库，cout、cin、endl 全在里面。忘了 include，std::cout 会报「未声明」。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string a = "大海";\n    string b = a + "航行";\n    if (a == b) {\n        cout << "同一片海" << endl;\n    } else {\n        cout << "不同海域" << endl;\n    }\n    cout << b << endl;\n    return 0;\n}',
          options: ['两行：同一片海 / 大海航行', '两行：不同海域 / 大海航行', '一行：不同海域大海航行', '报错'],
          answerIndex: 1,
          hint: 'a 是「大海」，b 是拼接后的新串，还相等吗？',
          explain: 'b = a + "航行" 得到「大海航行」，比 a 多两个字，a == b 不成立，走 else 输出「不同海域」；接着输出 b 的内容「大海航行」。string 的 == 严格比较内容。',
        },
        {
          kind: 'bug',
          prompt: '这段程序编译报错，问题出在哪一行？',
          code: ['using namespace std;', 'int main() {', '    cout << "起航" << endl;', '    return 0;', '}'],
          answerLine: 2,
          hint: 'cout 是谁带来的？',
          explain: '第 3 行用 cout，但整个文件没有 #include <iostream>，编译器不认识 cout，报 was not declared in this scope。using namespace std 只负责免前缀，库本身还是得 include。',
        },
        {
          kind: 'order',
          prompt: '把打乱的行排成程序：读入水手数再原样报数：',
          lines: ['#include <iostream>', 'using namespace std;', 'int main() {', '    int sailors;', '    cin >> sailors;', '    cout << sailors << endl;', '    return 0;', '}'],
          hint: '定义变量 → cin 读入 → cout 报数 → return 收工。',
          explain: '先用 int sailors; 准备舱位，cin >> sailors 卸货，cout << sailors 报数，return 0; 收工。>> 和 << 的方向别写反。',
        },
        {
          kind: 'output',
          prompt: '这段程序运行后输出什么？',
          code: '#include <iostream>\nusing namespace std;\nint main() {\n    int gem = 5;\n    int& twin = gem;\n    twin = 9;\n    cout << gem << endl;\n    return 0;\n}',
          options: ['9', '5', '14', '报错'],
          answerIndex: 0,
          hint: 'twin 是 gem 的别名。',
          explain: 'twin 是 gem 的引用，twin = 9 改的就是 gem，输出 9。同一块内存，两块名牌。',
        },
        {
          kind: 'fill',
          prompt: '补全读入语句，把敲进键盘的水手数装进变量：',
          code: 'int sailors;\n___ >> sailors;   // 等待玩家输入\ncout << sailors << endl;',
          answers: ['cin'],
          placeholder: '键盘传送带的名字',
          hint: '和 cout 相对的那位。',
          explain: 'cin 是标准输入流，>> 把键盘输入送进变量。方向是 >>（往里卸），别写成 <<。',
        },
        {
          kind: 'choice',
          prompt: '写完 using namespace std; 之后，下面哪句是对的？',
          options: ['cout 可以省略 std:: 直接写', '可以不再写 #include', 'std::cout 变成非法写法', '程序会自动变快'],
          answerIndex: 0,
          hint: 'using 只是省前缀，库还是要请。',
          explain: 'using namespace std; 只是让你省掉 std:: 前缀；#include 还是必须写，std::cout 这种完整写法依然合法。它也不影响速度——只是张名字便利贴。',
        },
      ],
    },
  ],
}
