import type { CourseDef } from './course'

/**
 * 首期课程：Python 基础。
 * 区域 1「变量平原」内容完整（3 关 + Boss，五种题型混编）；区域 2-5 为后续版本预告位。
 */
export const pythonBasics: CourseDef = {
  id: 'python-basics',
  title: '代码群岛',
  subtitle: 'Code Isles · 用像素冒险学正经知识 · 首期课程：Python 基础',
  regions: [
    {
      id: '1',
      name: '变量平原',
      tagline: '冒险从给宝箱贴标签开始',
      levels: [
        {
          id: '1-1',
          name: '贴标签的宝箱',
          xp: 30,
          gold: 10,
          learn: {
            title: '变量：给数据贴上标签',
            body: [
              '变量就像贴了标签的宝箱：name = "冒险者" 表示把字符串「冒险者」放进名叫 name 的宝箱里。',
              '赋值用单个等号 =，含义是「把右边的东西放进左边的变量」，不是数学里的"相等"。',
              '变量名规则：只能用字母、数字、下划线，且不能以数字开头；变量名区分大小写，hp 和 Hp 是两个不同的变量。',
            ],
            code: 'name = "冒险者"\nhp = 100\nhp = hp + 10      # 现在 hp 是 110',
          },
          questions: [
            {
              kind: 'choice',
              prompt: '下列哪一个是合法的变量名？',
              options: ['2nd_place', 'my_gold', 'my-gold', 'class'],
              answerIndex: 1,
              hint: '变量名里只能有字母、数字、下划线三种字符；还要避开一份叫「关键字」的保留名单。',
              explain: '变量名不能以数字开头（2nd_place ✗），不能含连字符（my-gold ✗，会被当成减法），class 是 Python 保留关键字（✗）；my_gold 完全合法。',
            },
            {
              kind: 'choice',
              prompt: '运行这段代码会发生什么？',
              code: 'hp = 100\nHp\n# 顺便一提：直接写一个变量名，就会输出它的值',
              options: ['输出 100', '报错：Hp 未定义', '输出 0', '输出 None'],
              answerIndex: 1,
              hint: '变量名大小写不同，就是两个不同的变量。',
              explain: '变量名区分大小写，hp 和 Hp 是两个不同的变量。只赋值过 hp，访问 Hp 会触发 NameError（未定义）。',
            },
            {
              kind: 'choice',
              prompt: '执行下面两行后，gold 的值是多少？',
              code: 'gold = 50\ngold = gold + 10',
              options: ['50', '10', '60', '报错'],
              answerIndex: 2,
              hint: '等号右边先算完，再放进左边的变量。',
              explain: '右边先算出 gold + 10 = 60，再放回变量 gold。变量可以随时被新值覆盖，这是「更新」变量的标准写法。',
            },
            {
              kind: 'choice',
              prompt: '执行后 b 的值是？',
              code: 'a = 3\nb = a\na = 7',
              options: ['7', '3', '10', '报错'],
              answerIndex: 1,
              hint: 'b 拿到的是「当时」的值，之后 a 的变化不会追溯。',
              explain: 'b = a 是把 a「当时」的值 3 交给 b；之后 a 改成 7，与 b 已经无关。',
            },
            {
              kind: 'choice',
              prompt: '先执行 x = 5，再执行 x = "五"，结果是？',
              options: ['报错：类型不能变', 'x 变成字符串「五」，完全合法', 'x 变成「55」', 'x 仍是 5'],
              answerIndex: 1,
              hint: 'Python 对变量不设类型门禁，最后一次赋值说了算。',
              explain: 'Python 的变量没有固定类型，重新赋值为另一种类型完全允许；x 只保留最后一次放进去的值。',
            },
          ],
        },
        {
          id: '1-2',
          name: '数字三兄弟',
          xp: 35,
          gold: 12,
          learn: {
            title: '数字与运算符：/ // % **',
            body: [
              'Python 最常用的两种数：整数（int）如 100，小数（float）如 3.5。',
              '基本运算符：+ 加、- 减、* 乘、/ 除，还有三个兄弟：// 整除、% 取余、** 乘方。',
              '记住分工：/ 的结果一定是小数；// 是丢掉小数部分的除法；% 取余数——判断奇偶、分组排队都靠它。',
            ],
            code: '7 / 2    # → 3.5   （除法，结果是小数）\n7 // 2   # → 3     （整除，丢掉小数）\n7 % 2    # → 1     （余数）\n2 ** 3   # → 8     （2 的 3 次方）',
          },
          questions: [
            {
              kind: 'choice',
              prompt: '7 // 2 的结果是？',
              options: ['3.5', '3', '4', '1'],
              answerIndex: 1,
              hint: '// 会把小数部分整个丢掉。',
              explain: '// 是整除（向下取整）：7 除以 2 商 3 余 1，// 给出商 3，丢掉余数。',
            },
            {
              kind: 'choice',
              prompt: '7 % 2 的结果是？',
              options: ['3', '3.5', '1', '0'],
              answerIndex: 2,
              hint: '想想余数：7 = 2 × 几 + 几？',
              explain: '% 取余数：7 = 2×3 + 1，余 1。判断奇偶的经典写法：n % 2 为 0 就是偶数。',
            },
            {
              kind: 'choice',
              prompt: '2 ** 3 的结果是？',
              options: ['6', '8', '9', '5'],
              answerIndex: 1,
              hint: '** 不是乘法，是「几次方」。',
              explain: '** 是乘方：2**3 = 2×2×2 = 8。别和乘法 2×3=6 弄混。',
            },
            {
              kind: 'choice',
              prompt: '10 / 5 的值和类型是？',
              options: ['整数 2', '小数 2.0', '报错', '字符串「2」'],
              answerIndex: 1,
              hint: '/ 从来不给整数结果。',
              explain: '只要用了 /，结果一律是小数（float）：10 / 5 得 2.0 而不是 2。想要整数商请用 //。',
            },
            {
              kind: 'choice',
              prompt: '3 + 2 * 2 的结果是？',
              options: ['10', '7', '12', '5'],
              answerIndex: 1,
              hint: '先乘除，后加减。',
              explain: '先乘除后加减：2×2=4，3+4=7。想先算加法要加括号：(3+2)*2 得 10。',
            },
            {
              kind: 'order',
              prompt: '把这三行排成能顺利执行的顺序（后一行要用到前面的变量）：',
              lines: ['gold = 50', 'gold = gold + 10', 'hp = gold - 30'],
              hint: '用到谁，谁就要先出现。',
              explain: '程序从上往下一行行执行：先有 gold，再更新 gold，最后才轮到用 gold 算 hp。变量必须先赋值再使用。',
            },
          ],
        },
        {
          id: '1-3',
          name: '会说话的卷轴',
          xp: 35,
          gold: 12,
          learn: {
            title: '字符串：让游戏开口说话',
            body: [
              '用引号包起来的文字就是字符串（str），单引号双引号都行：「火把」和 "火把" 是同一个东西。',
              '字符串也能做运算：+ 把两段文字拼起来，* 把文字重复几遍。',
              'len(...) 数字符个数；f-string 把变量嵌进文字：f"金币:{gold}" 里的 {gold} 会自动换成变量的值。',
            ],
            code: 'name = "冒险者"\ngold = 99\ntitle = f"{name} 的金币: {gold}"   # → 「冒险者 的金币: 99」\nlen("code")   # → 4\n"哈" * 3      # → 「哈哈哈」',
          },
          questions: [
            {
              kind: 'choice',
              prompt: '"火" + "把" 的结果是？',
              options: ['「火把」', '「火 把」', '报错', '「火+把」'],
              answerIndex: 0,
              hint: '字符串的加法不会自动补空格。',
              explain: '字符串的 + 是拼接：两段文字首尾相连，中间不会自动加空格。',
            },
            {
              kind: 'choice',
              prompt: '"哈" * 3 的结果是？',
              options: ['「哈哈」', '「哈哈哈」', '「哈3」', '报错'],
              answerIndex: 1,
              hint: '字符串 × 整数 = 复读机。',
              explain: '字符串 * 整数 = 重复三遍，得「哈哈哈」。字符串不能乘字符串，也不能乘小数。',
            },
            {
              kind: 'choice',
              prompt: 'len("code") 的结果是？',
              options: ['3', '4', '5', '报错'],
              answerIndex: 1,
              hint: '一个一个字符数。',
              explain: 'len() 返回字符个数：c-o-d-e 共 4 个字符。',
            },
            {
              kind: 'choice',
              prompt: '执行后得到什么？',
              code: 'name = "月"\nf"你好{name}"',
              options: ['「你好name」', '「你好月」', '报错', '「你好{name}」'],
              answerIndex: 1,
              hint: '注意字符串最前面那个字母 f。',
              explain: 'f-string 会把 {} 里的变量名换成它的值，得「你好月」。漏写 f 前缀就不会替换，原样输出。',
            },
            {
              kind: 'output',
              prompt: '这段代码运行后输出什么？',
              code: 'age = 12\n"我" + age',
              options: ['「我12」', '「我age」', '报错：文字不能加数字', '「我 12」'],
              answerIndex: 2,
              hint: '文字和数字是两种类型，加号不认识它们站在一起。',
              explain: '字符串只能拼接字符串。想得到「我12」要写 str(age) 或 f"我{age}"——这是新手最常见的报错之一。',
            },
            {
              kind: 'fill',
              prompt: '补全代码，让它数出 "code" 的字符个数（填一个函数名）：',
              code: '___("code")   # → 4',
              answers: ['len'],
              placeholder: '三个字母的函数名',
              hint: '以字母 l 开头，意为 length（长度）。',
              explain: 'len() 是最常用的内建函数之一，返回字符串（以后还有列表）的长度。',
            },
          ],
        },
        {
          id: '1-B',
          name: '变量平原大测验',
          xp: 80,
          gold: 30,
          boss: true,
          learn: {
            title: 'Boss 来了：平原全线复习',
            body: [
              '这一关没有新知识，9 道题覆盖前面三关，五种题型轮番上阵——答错会当场给解析，放心冲。',
              '全对零提示才能拿到 ★★★ 和完整战利品。整理行囊，出发！',
            ],
          },
          questions: [
            {
              kind: 'choice',
              prompt: '执行后 hp 的值是？',
              code: 'hp = 100\nhp = hp - 30',
              options: ['70', '100', '-30', '报错'],
              answerIndex: 0,
              hint: '先算右边，再存回去。',
              explain: '先算右边 100 - 30 = 70，再存回 hp。这就是变量的「更新」。',
            },
            {
              kind: 'choice',
              prompt: '下列哪一个是合法的变量名？',
              options: ['for', '_hp', '2d', 'my-hp'],
              answerIndex: 1,
              hint: '关键字名单、数字开头、连字符——逐一排除。',
              explain: 'for 是保留关键字；2d 以数字开头；my-hp 含连字符；下划线开头的 _hp 合法（习惯上表示"内部使用"）。',
            },
            {
              kind: 'choice',
              prompt: '9 // 4 + 9 % 4 的结果是？',
              options: ['3', '4', '2.25', '13'],
              answerIndex: 0,
              hint: '整除和取余各算各的，再相加。',
              explain: '9//4=2（商），9%4=1（余），2+1=3。整除和取余是一对搭档：商×除数+余数=被除数。',
            },
            {
              kind: 'output',
              prompt: '这段代码运行后输出什么？',
              code: '"3" + "4"',
              options: ['7（数字相加）', '「34」（文字拼接）', '报错', '「7」'],
              answerIndex: 1,
              hint: '带引号的是文字，不是数字。',
              explain: '带引号的是字符串，+ 表示拼接，得「34」。想算 7 要写 3 + 4（不带引号）。',
            },
            {
              kind: 'order',
              prompt: '把这三行排成能顺利执行的顺序：',
              lines: ['gold = 99', 'title = f"金币:{gold}"', 'len(title)'],
              hint: 'f-string 里的 {gold}，得先有 gold 才行。',
              explain: '先准备变量，再把它嵌进 f-string，最后才能对结果取长度。顺序错了就会 NameError。',
            },
            {
              kind: 'bug',
              prompt: '下面三行里，哪一行会报错？',
              code: ['name = "月"', 'age = 12', 'msg = name + age'],
              answerLine: 2,
              hint: '想想文字能不能直接加数字。',
              explain: '第 3 行把字符串和整数相加，触发 TypeError。想拼出「月12」要写 name + str(age)。',
            },
            {
              kind: 'choice',
              prompt: 'len("像素岛") 的结果是？',
              options: ['2', '3', '6', '9'],
              answerIndex: 1,
              hint: '一个汉字就是一个字符。',
              explain: 'len 数的是字符个数，每个汉字算 1 个字符，共 3 个。',
            },
            {
              kind: 'choice',
              prompt: '执行后 score 的值是？',
              code: 'score = 10\nscore = score * 2 + 4',
              options: ['24', '28', '48', '44'],
              answerIndex: 0,
              hint: '乘法优先。',
              explain: '先乘后加：10×2+4=24。运算优先级在赋值右边照样生效。',
            },
            {
              kind: 'output',
              prompt: '执行后得到什么？',
              code: 'gold = 99\nf"金币:{gold}"',
              options: ['「金币:{gold}」', '「金币:99」', '报错', '「金币:gold」'],
              answerIndex: 1,
              hint: 'f-string 会替换大括号里的东西。',
              explain: 'f-string 把 {gold} 替换成变量的值 99。Boss 战顺利，平原已在脚下！',
            },
          ],
        },
      ],
    },
    {
      id: '2',
      name: '分支森林',
      tagline: '每条岔路都是一次选择',
      comingSoon: true,
      levels: [],
    },
    {
      id: '3',
      name: '循环洞窟',
      tagline: '重复的活儿交给咒语',
      comingSoon: true,
      levels: [],
    },
    {
      id: '4',
      name: '列表湖',
      tagline: '一网打尽一串宝物',
      comingSoon: true,
      levels: [],
    },
    {
      id: '5',
      name: '字典城',
      tagline: '有名字的宝箱城',
      comingSoon: true,
      levels: [],
    },
  ],
}
